const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const FAMILY_BATCH_1_ARTICLES=[
 {id:"fb1-1001",number:"第1001條",title:"夫妻同居義務",content:"夫妻互負同居之義務；有不能同居之正當理由者，不在此限。",chapter:"婚姻效力",villageId:"family"},
 {id:"fb1-1018",number:"第1018條",title:"夫妻各自管理財產",content:"夫或妻各自管理、使用、收益及處分其財產。",chapter:"夫妻財產制",villageId:"family"},
 {id:"fb1-1050",number:"第1050條",title:"兩願離婚方式",content:"兩願離婚須以書面為之，有二人以上證人簽名並向戶政機關辦理離婚登記。",chapter:"離婚",villageId:"family"},
 {id:"fb1-1088",number:"第1088條",title:"未成年子女特有財產",content:"未成年子女特有財產由父母共同管理；父母非為子女利益不得處分。",chapter:"父母子女",villageId:"family"},
 {id:"fb1-1117",number:"第1117條",title:"受扶養權利者要件",content:"受扶養權利者原則不能維持生活且無謀生能力；直系血親尊親屬不受無謀生能力限制。",chapter:"扶養",villageId:"family"},
];
export const FAMILY_BATCH_1_SCENARIOS=[
 {id:"family-021",villageId:"family",title:"安全疑慮下的暫時分居",chapter:"婚姻效力",difficulty:"medium",story:["小萱因配偶多次暴力威脅，暫時搬離共同住所，優先確保人身安全。"],question:"依民法第1001條，何者正確？",choices:[c(1,"有不能同居的正當理由時，不受同居義務拘束。",true,"正確。條文為同居義務設有正當理由例外。"),c(2,"夫妻必須在任何情況下同住。",false,"錯誤。不能同居有正當理由時例外。"),c(3,"分居必然使婚姻立即無效。",false,"錯誤。同居義務與婚姻是否成立不同。"),c(4,"只有對方書面同意才可暫離。",false,"錯誤。關鍵是是否有正當理由。")],relatedArticles:["fb1-1001"],essayPrompt:"說明夫妻同居義務及其正當理由例外。",essayHint:"先說原則，再討論安全等不能同居正當理由。",tags:["同居義務","婚姻效力"],imageUrl,legalBasis:"民法第1001條"},
 {id:"family-022",villageId:"family",title:"自己名下的婚後存款",chapter:"夫妻財產制",difficulty:"easy",story:["阿宏想用自己名下的婚後存款投資定存，配偶主張必須先取得同意。"],question:"依民法第1018條，何者正確？",choices:[c(1,"阿宏原則可自行管理、使用、收益及處分自己的財產。",true,"正確。第1018條採各自財產管理原則。"),c(2,"配偶當然可禁止所有處分。",false,"錯誤。條文規定各自管理處分。"),c(3,"婚後財產必然不能由一方管理。",false,"錯誤。第1018條正相反。"),c(4,"只有法院可處分個人存款。",false,"錯誤。無此一般限制。")],relatedArticles:["fb1-1018"],essayPrompt:"說明第1018條下夫妻財產管理的原則。",essayHint:"管理、使用、收益、處分均由各自為之。",tags:["夫妻財產","存款"],imageUrl,legalBasis:"民法第1018條"},
 {id:"family-023",villageId:"family",title:"未登記的離婚協議",chapter:"離婚",difficulty:"medium",story:["阿明與小雯簽好離婚協議，也有兩位證人簽名，但一直未到戶政事務所辦理離婚登記。"],question:"依民法第1050條，何者正確？",choices:[c(1,"尚未完成兩願離婚，因仍須向戶政機關登記。",true,"正確。書面、二人以上證人與登記均為要件。"),c(2,"有書面與證人即已離婚。",false,"錯誤。還須完成登記。"),c(3,"口頭同意比登記更重要。",false,"錯誤。條文明定書面與登記。"),c(4,"只需一位證人簽名。",false,"錯誤。須二人以上證人。")],relatedArticles:["fb1-1050"],essayPrompt:"列出兩願離婚的三項方式要件。",essayHint:"書面、二人以上證人簽名、戶政登記。",tags:["兩願離婚","戶政登記"],imageUrl,legalBasis:"民法第1050條"},
 {id:"family-024",villageId:"family",title:"子女受贈股票的處分",chapter:"父母子女",difficulty:"hard",story:["小宇受祖父贈與股票，父母為清償自己的信用卡債，想把股票賣掉。"],question:"依民法第1088條，何者正確？",choices:[c(1,"非為子女利益，父母不得處分小宇特有財產。",true,"正確。父母共同管理但處分須為子女利益。"),c(2,"父母可任意出售子女資產還自己的債。",false,"錯誤。處分受子女利益限制。"),c(3,"父母完全不能管理子女特有財產。",false,"錯誤。父母共同管理並有使用收益權。"),c(4,"祖父贈與物當然屬父母。",false,"錯誤。是未成年子女特有財產。")],relatedArticles:["fb1-1088"],essayPrompt:"說明父母管理未成年子女特有財產的權限與限制。",essayHint:"共同管理、使用收益、處分須為子女利益。",tags:["子女財產","父母管理"],imageUrl,legalBasis:"民法第1088條"},
 {id:"family-025",villageId:"family",title:"仍能零工的年長父親",chapter:"扶養",difficulty:"hard",story:["阿國年長後只能做零星工作，收入不足維持生活，子女認為他尚有工作能力便不用扶養。"],question:"依民法第1117條，何者正確？",choices:[c(1,"直系血親尊親屬不能維持生活時，不以無謀生能力為限。",true,"正確。尊親屬有無謀生能力限制的例外。"),c(2,"父親只要能做任何零工就絕無扶養請求。",false,"錯誤。尊親屬例外且仍看能否維持生活。"),c(3,"任何人有收入都可無條件請求扶養。",false,"錯誤。原則仍以不能維持生活為前提。"),c(4,"扶養與直系血親無關。",false,"錯誤。直系血親相互扶養受民法規範。")],relatedArticles:["fb1-1117"],essayPrompt:"說明受扶養權利者的原則要件與尊親屬例外。",essayHint:"不能維持生活、無謀生能力，以及尊親屬的例外。",tags:["扶養","尊親屬"],imageUrl,legalBasis:"民法第1117條"}
];
