const imageUrl="https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/obligation-016-C2jdVdwzMe8GTXf5KRNJqk.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const FAMILY_BATCH_2_ARTICLES=[
 {id:"fb2-1056",number:"第1056條",title:"判決離婚損害賠償",content:"因判決離婚受損者得向有過失他方請求賠償；無過失受害人得請求非財產損害賠償。",chapter:"離婚",villageId:"family"},
 {id:"fb2-1077",number:"第1077條",title:"收養的身分關係效力",content:"養子女與養父母及其親屬間原則與婚生子女同；收養存續中與本生父母親屬權利義務停止。",chapter:"收養",villageId:"family"},
 {id:"fb2-1090",number:"第1090條",title:"親權濫用的停止",content:"父母一方濫用子女權利時，法院得為子女利益宣告停止其全部或一部權利。",chapter:"父母子女",villageId:"family"},
 {id:"fb2-1092",number:"第1092條",title:"委託監護職務",content:"父母得因特定事項、於一定期限內，以書面委託他人行使監護職務。",chapter:"父母子女",villageId:"family"},
 {id:"fb2-1118",number:"第1118條",title:"扶養義務的免除或減輕",content:"扶養將使義務人不能維持自己生活者原則免除；受扶養人為尊親屬或配偶時減輕義務。",chapter:"扶養",villageId:"family"},
];
export const FAMILY_BATCH_2_SCENARIOS=[
 {id:"family-026",villageId:"family",title:"判決離婚後的精神損害",chapter:"離婚",difficulty:"hard",story:["小美無過失卻因配偶重大過錯而獲判離婚，並因此承受精神與財產損害。"],question:"依民法第1056條，何者正確？",choices:[c(1,"小美得向有過失配偶請求財產及非財產損害賠償。",true,"正確。無過失受害人可請求相當非財產損害賠償。"),c(2,"判決離婚一律不得請求賠償。",false,"錯誤。第1056條明定賠償救濟。"),c(3,"有過失配偶可向無過失方請求精神賠償。",false,"錯誤。非財產損害限無過失受害人。"),c(4,"只能請求精神損害，不能請求財產損害。",false,"錯誤。條文先規定損害賠償。")],relatedArticles:["fb2-1056"],essayPrompt:"說明第1056條財產與非財產損害賠償的要件。",essayHint:"判決離婚、有過失他方與無過失受害人的限制。",tags:["離婚","損害賠償"],imageUrl,legalBasis:"民法第1056條"},
 {id:"family-027",villageId:"family",title:"收養後的雙重家庭關係",chapter:"收養",difficulty:"hard",story:["小樂經法院認可被收養，家人詢問他與養父母及本生父母間的權利義務如何變化。"],question:"依民法第1077條，何者正確？",choices:[c(1,"與養父母及其親屬關係原則視同婚生子女；與本生家庭權利義務原則停止。",true,"正確。這是收養存續中的基本身分效力。"),c(2,"收養完全不改變任何身分關係。",false,"錯誤。收養影響養家與本生家庭權利義務。"),c(3,"與養父母關係低於一般子女。",false,"錯誤。原則與婚生子女同。"),c(4,"本生家庭關係必然永久消滅。",false,"錯誤。條文是收養關係存續中停止。")],relatedArticles:["fb2-1077"],essayPrompt:"說明收養存續中養家與本生家庭的關係。",essayHint:"養家視同婚生子女、本生家庭權利義務停止。",tags:["收養","身分關係"],imageUrl,legalBasis:"民法第1077條"},
 {id:"family-028",villageId:"family",title:"濫用親權的保護聲請",chapter:"父母子女",difficulty:"hard",story:["父親持續濫用對未成年子女的權利，傷害子女利益，母親希望法院介入。"],question:"依民法第1090條，何者正確？",choices:[c(1,"法院得為子女利益宣告停止父親全部或一部權利。",true,"正確。濫用親權時可由法院作停止宣告。"),c(2,"親權永遠不受法院監督。",false,"錯誤。法院可為子女利益介入。"),c(3,"只有父親同意才可停止。",false,"錯誤。可依他方等聲請或職權處理。"),c(4,"只能剝奪母親的權利。",false,"錯誤。濫用的一方均可能被停止。")],relatedArticles:["fb2-1090"],essayPrompt:"說明親權濫用時法院保護子女的方式。",essayHint:"濫用、子女利益、停止全部或一部權利。",tags:["親權","子女利益"],imageUrl,legalBasis:"民法第1090條"},
 {id:"family-029",villageId:"family",title:"出國期間的書面委託監護",chapter:"父母子女",difficulty:"medium",story:["父母因派駐海外半年，以書面委託祖母在此期間處理子女的就醫與學校特定事項。"],question:"依民法第1092條，何者正確？",choices:[c(1,"得以書面就特定事項、一定期限委託祖母行使監護職務。",true,"正確。三項要件為特定事項、一定期限及書面。"),c(2,"可永遠以口頭全面放棄親權。",false,"錯誤。條文要求書面、特定事項與一定期限。"),c(3,"父母絕不能委託監護職務。",false,"錯誤。第1092條允許合乎要件的委託。"),c(4,"只要祖母願意即可，不必有期間。",false,"錯誤。必須於一定期限內。")],relatedArticles:["fb2-1092"],essayPrompt:"列出第1092條委託監護職務的方式要件。",essayHint:"特定事項、一定期限、書面。",tags:["委託監護","祖父母"],imageUrl,legalBasis:"民法第1092條"},
 {id:"family-030",villageId:"family",title:"自身生活也難維持的扶養人",chapter:"扶養",difficulty:"hard",story:["阿誠收入微薄，扶養一般親屬會使自己無法維持基本生活；受扶養人改為其年長父親時，結果不同。"],question:"依民法第1118條，何者正確？",choices:[c(1,"一般情形可免除義務；受扶養人為尊親屬或配偶時則減輕義務。",true,"正確。條文區分免除與減輕。"),c(2,"任何扶養義務都絕不能調整。",false,"錯誤。第1118條設有調整規定。"),c(3,"尊親屬受扶養時一定完全免除。",false,"錯誤。是減輕而非免除。"),c(4,"只要收入低就完全不必考量對方身分。",false,"錯誤。尊親屬或配偶是特別類型。")],relatedArticles:["fb2-1118"],essayPrompt:"比較第1118條的免除與減輕扶養義務。",essayHint:"先看義務人能否維持自己生活，再看受扶養人身分。",tags:["扶養","免除","減輕"],imageUrl,legalBasis:"民法第1118條"}
];
