const imageUrl="https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/obligation-016-C2jdVdwzMe8GTXf5KRNJqk.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const FAMILY_BATCH_4_ARTICLES=[
 {id:"fb4-1060",number:"第1060條",title:"未成年子女住所",content:"未成年之子女，以其父母之住所為住所。",chapter:"父母子女",villageId:"family"},
 {id:"fb4-1078",number:"第1078條",title:"養子女姓氏",content:"養子女從收養者姓或維持原姓；夫妻共同收養時，登記前應書面約定從養父姓、養母姓或原姓。",chapter:"收養",villageId:"family"},
 {id:"fb4-1102",number:"第1102條",title:"監護人不得受讓財產",content:"監護人不得受讓受監護人之財產。",chapter:"監護",villageId:"family"},
 {id:"fb4-1119",number:"第1119條",title:"扶養程度",content:"扶養程度按受扶養權利者需要、負扶養義務者經濟能力及身分定之。",chapter:"扶養",villageId:"family"},
 {id:"fb4-1120",number:"第1120條",title:"扶養方法與扶養費爭議",content:"扶養方法協議不成由親屬會議定；扶養費給付協議不成由法院定。",chapter:"扶養",villageId:"family"},
];
export const FAMILY_BATCH_4_SCENARIOS=[
 {id:"family-036",villageId:"family",title:"隨父母遷居的未成年子女",chapter:"父母子女",difficulty:"easy",story:["小安未成年，父母共同遷居到新住所，親友詢問小安在民法上的住所如何認定。"],question:"依民法第1060條，何者正確？",choices:[c(1,"小安以父母住所為住所。",true,"正確。未成年子女住所從父母住所。"),c(2,"小安一定以學校地址為住所。",false,"錯誤。民法採父母住所。"),c(3,"小安可自行任意指定住所。",false,"錯誤。未成年子女受第1060條規範。"),c(4,"小安沒有法律上住所。",false,"錯誤。法律明定其住所。")],relatedArticles:["fb4-1060"],essayPrompt:"說明未成年子女住所的法律認定。",essayHint:"直接引用第1060條。",tags:["住所","未成年子女"],imageUrl,legalBasis:"民法第1060條"},
 {id:"family-037",villageId:"family",title:"共同收養前的姓氏約定",chapter:"收養",difficulty:"medium",story:["夫妻準備共同收養小樂，想在登記前決定小樂從養父姓、養母姓或維持原姓。"],question:"依民法第1078條，何者正確？",choices:[c(1,"應在收養登記前以書面約定三種姓氏選項之一。",true,"正確。條文設有書面約定與三種選擇。"),c(2,"養子女必須一律從養父姓。",false,"錯誤。可從養母姓或維持原姓。"),c(3,"只能登記後再口頭決定。",false,"錯誤。須登記前書面約定。"),c(4,"收養後一律不得維持原姓。",false,"錯誤。維持原姓是明文選項。")],relatedArticles:["fb4-1078"],essayPrompt:"說明夫妻共同收養時的姓氏選擇與方式。",essayHint:"登記前、書面、養父姓／養母姓／原姓。",tags:["收養","姓氏"],imageUrl,legalBasis:"民法第1078條"},
 {id:"family-038",villageId:"family",title:"監護人想買下被監護人房屋",chapter:"監護",difficulty:"hard",story:["監護人看中受監護人名下房屋，主張願意用市價買下，並請自己代為簽約。"],question:"依民法第1102條，何者正確？",choices:[c(1,"監護人不得受讓受監護人財產。",true,"正確。第1102條採直接禁止。"),c(2,"只要價格公平就一定可以。",false,"錯誤。條文並未設公平價格例外。"),c(3,"只要被監護人未成年即可買下。",false,"錯誤。監護關係不容此受讓。"),c(4,"由監護人自己批准即可。",false,"錯誤。受讓本身被禁止。")],relatedArticles:["fb4-1102"],essayPrompt:"說明第1102條禁止監護人受讓財產的目的。",essayHint:"防止監護人與被監護人利益衝突。",tags:["監護","利益衝突"],imageUrl,legalBasis:"民法第1102條"},
 {id:"family-039",villageId:"family",title:"扶養費不是固定金額",chapter:"扶養",difficulty:"medium",story:["兩名子女爭論父親扶養費應否一律固定為相同金額，但父親醫療需要與子女收入差異很大。"],question:"依民法第1119條，扶養程度應如何定？",choices:[c(1,"依父親需要、子女經濟能力及身分綜合決定。",true,"正確。這是第1119條三項基準。"),c(2,"所有扶養費一律固定平均。",false,"錯誤。法律採個案衡量。"),c(3,"只看受扶養人的想要金額。",false,"錯誤。也要看義務人能力與身分。"),c(4,"只看扶養人的收入而不看需要。",false,"錯誤。需要亦為法定基準。")],relatedArticles:["fb4-1119"],essayPrompt:"列出扶養程度的三項判斷基準。",essayHint:"需要、經濟能力、身分。",tags:["扶養費","經濟能力"],imageUrl,legalBasis:"民法第1119條"},
 {id:"family-040",villageId:"family",title:"扶養方式談不攏",chapter:"扶養",difficulty:"hard",story:["家人對父親要由誰照護、如何照護及每月扶養費都談不攏，需依法尋找決定方式。"],question:"依民法第1120條，何者正確？",choices:[c(1,"扶養方法協議不成由親屬會議定；扶養費協議不成由法院定。",true,"正確。條文區分兩類爭議。"),c(2,"兩種爭議都只能由法院決定。",false,"錯誤。扶養方法先由親屬會議定。"),c(3,"兩種爭議都只能由親屬會議定。",false,"錯誤。扶養費協議不成由法院定。"),c(4,"一旦談不攏就不必扶養。",false,"錯誤。法律提供決定機制。")],relatedArticles:["fb4-1120"],essayPrompt:"比較扶養方法與扶養費協議不成時的決定機制。",essayHint:"親屬會議與法院的不同角色。",tags:["扶養","親屬會議"],imageUrl,legalBasis:"民法第1120條"}
];
