const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const FAMILY_BATCH_3_ARTICLES=[
 {id:"fb3-1057",number:"第1057條",title:"判決離婚後的贍養費",content:"無過失配偶因判決離婚陷於生活困難時，他方縱無過失，亦應給與相當贍養費。",chapter:"離婚",villageId:"family"},
 {id:"fb3-1076-2",number:"第1076條之2",title:"未成年被收養者的同意",content:"七歲以下由法定代理人代為並代受意思表示；七歲以上未成年人被收養須法定代理人同意。",chapter:"收養",villageId:"family"},
 {id:"fb3-1093",number:"第1093條",title:"遺囑指定監護人",content:"最後行使、負擔未成年子女權利義務者得以遺囑指定監護人；受指定者知悉後十五日內應報告法院。",chapter:"監護",villageId:"family"},
 {id:"fb3-1100",number:"第1100條",title:"監護人的善良管理人注意",content:"監護人應以善良管理人之注意，執行監護職務。",chapter:"監護",villageId:"family"},
 {id:"fb3-1101",number:"第1101條",title:"受監護人財產的處分",content:"監護人非為受監護人利益不得處分其財產；代理處分不動產等重要行為非經法院許可不生效力。",chapter:"監護",villageId:"family"},
];
export const FAMILY_BATCH_3_SCENARIOS=[
 {id:"family-031",villageId:"family",title:"判決離婚後的生活困難",chapter:"離婚",difficulty:"hard",story:["小君無過失卻因判決離婚失去主要生活支持，離婚後陷入生活困難；前配偶同樣沒有過失。"],question:"依民法第1057條，何者正確？",choices:[c(1,"前配偶仍應給與小君相當贍養費。",true,"正確。另一方縱無過失，仍有相當贍養費義務。"),c(2,"只有有過失的一方才可能給付。",false,"錯誤。第1057條明定縱無過失亦應給付。"),c(3,"生活困難與離婚後贍養無關。",false,"錯誤。生活困難正是法定要件。"),c(4,"這一定是第1056條損害賠償。",false,"錯誤。贍養費與損害賠償不同。")],relatedArticles:["fb3-1057"],essayPrompt:"區別第1057條贍養費與第1056條損害賠償。",essayHint:"無過失、生活困難及他方縱無過失。",tags:["贍養費","離婚"],imageUrl,legalBasis:"民法第1057條"},
 {id:"family-032",villageId:"family",title:"十歲孩子的收養同意",chapter:"收養",difficulty:"medium",story:["十歲的小安將被收養，家人詢問小安的法定代理人是否需要表示同意。"],question:"依民法第1076條之2，何者正確？",choices:[c(1,"滿七歲的未成年人被收養，應得法定代理人同意。",true,"正確。七歲以上適用同意規則。"),c(2,"十歲兒童可完全自行決定。",false,"錯誤。仍須法定代理人同意。"),c(3,"任何年齡收養都由子女自行簽約。",false,"錯誤。七歲以下由代理人代為，七歲以上須同意。"),c(4,"收養不需要任何法定代理人參與。",false,"錯誤。未成年收養有特別規定。")],relatedArticles:["fb3-1076-2"],essayPrompt:"比較七歲以下與七歲以上未成年人收養時的意思表示規則。",essayHint:"代為並代受、法定代理人同意。",tags:["收養","未成年人"],imageUrl,legalBasis:"民法第1076條之2"},
 {id:"family-033",villageId:"family",title:"遺囑指定的監護人",chapter:"監護",difficulty:"hard",story:["最後單獨照顧子女的母親，以遺囑指定阿姨為監護人；阿姨知悉後遲遲未向法院報告。"],question:"依民法第1093條，何者正確？",choices:[c(1,"阿姨知悉後十五日內應報告法院，逾期未報告視為拒絕就職。",true,"正確。條文設有十五日報告與視為拒絕規則。"),c(2,"遺囑指定後不必有任何程序。",false,"錯誤。須向法院報告。"),c(3,"任何親友都可不經遺囑自動優先。",false,"錯誤。題目是遺囑指定的特別制度。"),c(4,"監護人知悉後可無限期決定。",false,"錯誤。有十五日期限。")],relatedArticles:["fb3-1093"],essayPrompt:"說明遺囑指定監護人與報告期限。",essayHint:"最後行使親權者、遺囑、十五日、視為拒絕。",tags:["監護","遺囑"],imageUrl,legalBasis:"民法第1093條"},
 {id:"family-034",villageId:"family",title:"監護人疏於管理財產",chapter:"監護",difficulty:"medium",story:["監護人把被監護人存款隨意放在無利息且高風險的私人帳戶，長期不查核。"],question:"依民法第1100條，應以何標準評價？",choices:[c(1,"監護人應以善良管理人注意執行職務。",true,"正確。第1100條是監護職務的一般注意義務。"),c(2,"監護人可完全依個人喜好管理。",false,"錯誤。受善良管理人注意標準拘束。"),c(3,"監護人對財產管理沒有責任。",false,"錯誤。條文明定注意義務。"),c(4,"只要是親屬就不受任何標準。",false,"錯誤。身分不排除注意義務。")],relatedArticles:["fb3-1100"],essayPrompt:"說明監護人執行職務的注意義務。",essayHint:"善良管理人注意與被監護人利益。",tags:["監護","善良管理人"],imageUrl,legalBasis:"民法第1100條"},
 {id:"family-035",villageId:"family",title:"監護人出售被監護人房屋",chapter:"監護",difficulty:"hard",story:["監護人想賣掉受監護人名下房屋清償自己的債務，且未向法院申請許可。"],question:"依民法第1101條，何者正確？",choices:[c(1,"非為受監護人利益不得處分；處分不動產未經法院許可不生效力。",true,"正確。兩項限制均適用。"),c(2,"監護人可用其名下房屋清償自己的債。",false,"錯誤。非為受監護人利益不得處分。"),c(3,"不動產處分只要監護人簽字就有效。",false,"錯誤。須法院許可。"),c(4,"法院許可只影響金額，不影響效力。",false,"錯誤。未經許可不生效力。")],relatedArticles:["fb3-1101"],essayPrompt:"說明監護人處分受監護人財產的利益限制與法院許可。",essayHint:"受監護人利益、不動產、未經許可不生效。",tags:["監護","不動產","法院許可"],imageUrl,legalBasis:"民法第1101條"}
];
