const imageUrl = "https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/general-015-A7F4HKZTwHjsmpiu86gxsG.webp";

export const GENERAL_BATCH_1_ARTICLES = [
  { id: "gb1-art3", number: "第3條", title: "簽名、印章與指印", content: "依法律之規定，有使用文字之必要者，得不由本人自寫，但必須親自簽名。如有用印章代簽名者，其蓋章與簽名生同等之效力。如以指印、十字或其他符號代簽名者，在文件上，經二人簽名證明，亦與簽名生同等之效力。", chapter: "法例", villageId: "general" },
  { id: "gb1-art4", number: "第4條", title: "文字與號碼不符合", content: "關於一定之數量，同時以文字及號碼表示者，其文字與號碼有不符合時，如法院不能決定何者為當事人之原意，應以文字為準。", chapter: "法例", villageId: "general" },
  { id: "gb1-art68", number: "第68條", title: "從物", content: "非主物之成分，常助主物之效用，而同屬於一人者，為從物。但交易上有特別習慣者，依其習慣。主物之處分，及於從物。", chapter: "物", villageId: "general" },
  { id: "gb1-art69", number: "第69條", title: "天然孳息與法定孳息", content: "稱天然孳息者，謂果實、動物之產物及其他依物之用法所收穫之出產物。稱法定孳息者，謂利息、租金及其他因法律關係所得之收益。", chapter: "物", villageId: "general" },
  { id: "gb1-art95", number: "第95條", title: "非對話意思表示的到達", content: "非對話而為意思表示者，其意思表示，以通知達到相對人時，發生效力。但撤回之通知，同時或先時到達者，不在此限。表意人於發出通知後死亡或喪失行為能力或其行為能力受限制者，其意思表示，不因之失其效力。", chapter: "意思表示", villageId: "general" },
];

export const GENERAL_BATCH_1_SCENARIOS = [
  { id: "general-021", villageId: "general", title: "代筆文件與印章簽署", chapter: "法例", difficulty: "easy", story: ["林小姐因手部受傷，請朋友代寫依法須以書面作成的土地租約。", "完成後，她親自蓋上平日使用的印章。", "房東認為不是親筆寫、也不是親筆簽名，租約一定無效。"], question: "依民法第3條，下列何者正確？", choices: [{ id: 1, text: "文字可代寫；本人親自蓋章代簽名時，蓋章與簽名具同等效力。", isCorrect: true, explanation: "正確。文字可不由本人自寫；印章代簽名與簽名同效。" }, { id: 2, text: "只要不是本人親筆寫，文件當然無效。", isCorrect: false, explanation: "錯誤。法律容許文字由他人代寫。" }, { id: 3, text: "印章永遠只能作為參考，不能代替簽名。", isCorrect: false, explanation: "錯誤。第3條明定蓋章代簽名與簽名同效。" }, { id: 4, text: "只有指印可替代簽名，印章不可。", isCorrect: false, explanation: "錯誤。指印另須二人簽名證明；印章可代簽名。" }], relatedArticles: ["gb1-art3"], essayPrompt: "請比較代筆文字、蓋章與指印在第3條下的要件。", essayHint: "請分別說明文字、印章及指印的法律效果。", tags: ["簽名", "印章", "書面"], imageUrl, explanation: "民法第3條允許代筆文字與印章代簽名。", legalBasis: "民法第3條" },
  { id: "general-022", villageId: "general", title: "訂單金額的文字與號碼不同", chapter: "法例", difficulty: "easy", story: ["早餐店老闆訂購冷藏櫃。", "訂單同時寫著『新臺幣拾貳萬元整』與『120,0000』。", "法院無法從往來紀錄判斷雙方真正合意的數額。"], question: "依民法第4條，法院應如何處理？", choices: [{ id: 1, text: "若不能決定當事人原意，應以文字表示的數量為準。", isCorrect: true, explanation: "正確。第4條明定此時應以文字為準。" }, { id: 2, text: "一律以阿拉伯數字為準。", isCorrect: false, explanation: "錯誤。條文沒有採數字優先。" }, { id: 3, text: "文字與號碼不同時，契約當然無效。", isCorrect: false, explanation: "錯誤。應先探求真意，無法決定才採文字。" }, { id: 4, text: "由出賣人單方選擇採文字或數字。", isCorrect: false, explanation: "錯誤。法律沒有給任一方單方選擇權。" }], relatedArticles: ["gb1-art4"], essayPrompt: "若通訊紀錄可證明真意，是否仍必須以文字為準？", essayHint: "先討論真意能否決定，再說明補充規則。", tags: ["數量", "契約", "文字"], imageUrl, explanation: "第4條是無法決定真意時的補充規則。", legalBasis: "民法第4條" },
  { id: "general-023", villageId: "general", title: "出售咖啡車時的專用磨豆機", chapter: "物", difficulty: "medium", story: ["阿哲出售自己的行動咖啡車。", "車上的專用磨豆機不是車體零件，卻長期固定搭配咖啡車營運，且兩者都屬阿哲所有。", "契約只寫出售咖啡車，買方主張磨豆機也一併移轉。"], question: "依民法第68條，下列何者最符合規定？", choices: [{ id: 1, text: "如磨豆機非主物成分、常助主物效用且同屬一人，原則上為從物，主物處分及於從物。", isCorrect: true, explanation: "正確。這是從物的構成要件與效果。" }, { id: 2, text: "只要不是主物成分，就絕不會隨主物移轉。", isCorrect: false, explanation: "錯誤。符合從物要件時，主物處分及於從物。" }, { id: 3, text: "買方主張需要時，附近設備都會移轉。", isCorrect: false, explanation: "錯誤。仍須符合從物要件。" }, { id: 4, text: "從物制度只適用租賃，不適用買賣。", isCorrect: false, explanation: "錯誤。第68條並無此限制。" }], relatedArticles: ["gb1-art68"], essayPrompt: "若磨豆機是向第三人租用，結論可能如何改變？", essayHint: "檢驗同屬一人與交易習慣兩項要素。", tags: ["從物", "主物", "買賣"], imageUrl, explanation: "主物處分及於符合要件的從物。", legalBasis: "民法第68條" },
  { id: "general-024", villageId: "general", title: "果園收成與店面租金", chapter: "物", difficulty: "easy", story: ["陳先生擁有一座芒果園，也把一樓店面出租給飲料店。", "芒果成熟採收後，他收到每月店面租金。", "承租人認為兩者都是同一類孳息。"], question: "依民法第69條，下列何者正確？", choices: [{ id: 1, text: "芒果屬天然孳息；租金屬法定孳息。", isCorrect: true, explanation: "正確。果實是天然孳息，租金是因法律關係所得的法定孳息。" }, { id: 2, text: "芒果與租金都屬天然孳息。", isCorrect: false, explanation: "錯誤。租金屬法定孳息。" }, { id: 3, text: "芒果與租金都屬法定孳息。", isCorrect: false, explanation: "錯誤。果實為天然孳息。" }, { id: 4, text: "孳息只包括現金收入，不包括果實。", isCorrect: false, explanation: "錯誤。條文明列果實。" }], relatedArticles: ["gb1-art69"], essayPrompt: "請各舉一例說明天然孳息與法定孳息。", essayHint: "從果實、利息、租金與法律關係收益比較。", tags: ["孳息", "果實", "租金"], imageUrl, explanation: "第69條區分天然孳息與法定孳息。", legalBasis: "民法第69條" },
  { id: "general-025", villageId: "general", title: "撤回通知與信件到達", chapter: "意思表示", difficulty: "medium", story: ["設計師小芸以掛號信通知客戶終止合作。", "信件週一上午送達客戶授權收件的公司總務；小芸週一下午才寄出撤回通知。", "她擔心寄信後若喪失行為能力，原通知是否還有效。"], question: "依民法第95條，下列何者最符合規定？", choices: [{ id: 1, text: "終止通知到達相對人時生效；撤回通知須同時或先到達才可阻卻效力。", isCorrect: true, explanation: "正確。第95條採到達主義，並規定撤回通知的到達時點。" }, { id: 2, text: "非對話通知一投入郵筒即生效。", isCorrect: false, explanation: "錯誤。原則上須通知到達相對人。" }, { id: 3, text: "表意人寄信後行為能力受限制，原通知當然失效。", isCorrect: false, explanation: "錯誤。第95條第2項規定不因而失效。" }, { id: 4, text: "撤回通知只要七日內寄出即必定優先。", isCorrect: false, explanation: "錯誤。關鍵在同時或先到達。" }], relatedArticles: ["gb1-art95"], essayPrompt: "若撤回通知與原通知同時到達，法律效果為何？", essayHint: "依第95條第1項的例外處理。", tags: ["意思表示", "到達", "撤回"], imageUrl, explanation: "非對話意思表示以到達相對人時生效。", legalBasis: "民法第95條" },
];
