const imageUrl = "images/general-016-twt7sfi6gxnrkiwvy3w8g9-a0717a94a14c.webp";
const choice = (id: number, text: string, isCorrect: boolean, explanation: string) => ({ id, text, isCorrect, explanation });
export const GENERAL_BATCH_2_ARTICLES = [
  { id:"gb2-art5",number:"第5條",title:"數次表示數量不一致",content:"關於一定之數量，以文字或號碼為數次之表示者，其表示有不符合時，如法院不能決定何者為當事人之原意，應以最低額為準。",chapter:"法例",villageId:"general" },
  { id:"gb2-art8",number:"第8條",title:"死亡宣告",content:"失蹤人失蹤滿七年後，法院得因利害關係人或檢察官之聲請，為死亡之宣告。失蹤人為八十歲以上者，得於失蹤滿三年後為死亡宣告。失蹤人為遭遇特別災難者，得於特別災難終了滿一年後為死亡宣告。",chapter:"自然人",villageId:"general" },
  { id:"gb2-art20",number:"第20條",title:"住所設定",content:"依一定事實，足認以久住之意思，住於一定之地域者，即為設定其住所於該地。一人同時不得有兩住所。",chapter:"自然人",villageId:"general" },
  { id:"gb2-art21",number:"第21條",title:"法定代理人住所",content:"無行為能力人及限制行為能力人，以其法定代理人之住所為住所。",chapter:"自然人",villageId:"general" },
  { id:"gb2-art25",number:"第25條",title:"法人成立",content:"法人非依本法或其他法律之規定，不得成立。",chapter:"法人",villageId:"general" },
];
export const GENERAL_BATCH_2_SCENARIOS = [
  {id:"general-026",villageId:"general",title:"報價單寫了三種金額",chapter:"法例",difficulty:"medium",story:["阿隆的裝潢報價單，對同一張書桌寫了一萬元、貳萬元及30,000元。","雙方都無法證明真正合意的數額。"],question:"依民法第5條，法院應如何處理？",choices:[choice(1,"以最後記載的三萬元為準。",false,"錯誤。條文沒有最後記載優先規則。"),choice(2,"以最低額一萬元為準。",true,"正確。無法決定真意時，以最低額為準。"),choice(3,"以文字貳萬元為準。",false,"錯誤。第5條是數次表示不一致時採最低額。"),choice(4,"報價單當然無效。",false,"錯誤。第5條提供補充規則。")],relatedArticles:["gb2-art5"],essayPrompt:"比較第4條與第5條的適用情形。",essayHint:"從一次與數次表示的差別分析。",tags:["數量","報價","真意"],imageUrl,explanation:"數次表示數量不一致且真意不明時採最低額。",legalBasis:"民法第5條"},
  {id:"general-027",villageId:"general",title:"海難後的失蹤親人",chapter:"自然人",difficulty:"medium",story:["阿姨在颱風海難中失蹤，事故結束已滿一年仍無消息。","家人想處理她名下的財產。"],question:"依民法第8條，下列何者正確？",choices:[choice(1,"必須等失蹤滿七年。",false,"錯誤。特別災難有滿一年規定。"),choice(2,"家屬自行公告即可視為死亡。",false,"錯誤。須由法院為死亡宣告。"),choice(3,"災難終了滿一年後，利害關係人得向法院聲請死亡宣告。",true,"正確。這是特別災難的特別期間。"),choice(4,"滿三個月就可聲請。",false,"錯誤。第8條未規定三個月。")],relatedArticles:["gb2-art8"],essayPrompt:"比較一般失蹤與特別災難失蹤的期間。",essayHint:"注意第8條的三種期間。",tags:["失蹤","死亡宣告","災難"],imageUrl,explanation:"特別災難終了滿一年後得聲請死亡宣告。",legalBasis:"民法第8條"},
  {id:"general-028",villageId:"general",title:"工作地租屋是否成為住所",chapter:"自然人",difficulty:"medium",story:["小志在台中租屋工作三年，工作與生活重心都在台中，並計畫長住。","他在父母家仍有一間房。"],question:"依民法第20條，下列何者正確？",choices:[choice(1,"只要租屋就必定有第二住所。",false,"錯誤。一人同時不得有兩住所。"),choice(2,"戶籍地永遠就是法律住所。",false,"錯誤。須看居住事實與久住意思。"),choice(3,"工作三年必定自動變更住所。",false,"錯誤。仍須綜合事實判斷。"),choice(4,"須依久住意思與居住事實判斷是否設定住所。",true,"正確。第20條採此一標準。")],relatedArticles:["gb2-art20"],essayPrompt:"列出判斷久住意思的客觀事實。",essayHint:"從居住、工作、生活安排分析。",tags:["住所","久住","租屋"],imageUrl,explanation:"住所以久住意思與客觀居住事實判斷。",legalBasis:"民法第20條"},
  {id:"general-029",villageId:"general",title:"未成年人的法律住所",chapter:"自然人",difficulty:"easy",story:["國中生小晴因讀書暫住外婆家，父母仍共同行使親權並住在新竹。","程序上需要判斷她的法律住所。"],question:"依民法第21條，何者正確？",choices:[choice(1,"以外婆住處當然為住所。",false,"錯誤。暫住不改變第21條規定。"),choice(2,"以法定代理人的住所為住所。",true,"正確。限制行為能力人以法定代理人住所為住所。"),choice(3,"未成年人沒有住所。",false,"錯誤。法律明定認定方式。"),choice(4,"由未成年人自行選擇。",false,"錯誤。不能任意選擇。")],relatedArticles:["gb2-art21"],essayPrompt:"若改由監護人擔任法定代理人，如何分析？",essayHint:"抓住法定代理人住所。",tags:["住所","未成年人","法定代理人"],imageUrl,explanation:"限制行為能力人以法定代理人住所為住所。",legalBasis:"民法第21條"},
  {id:"general-030",villageId:"general",title:"讀書會能否自稱法人簽約",chapter:"法人",difficulty:"easy",story:["社區讀書會想租場地，自稱『晨光基金會』並以法人名義簽約。","但團體未依任何法律完成法人設立程序。"],question:"依民法第25條，何者正確？",choices:[choice(1,"有十位成員就當然成為法人。",false,"錯誤。法人須依法成立。"),choice(2,"自稱基金會就當然有法人格。",false,"錯誤。名稱不等於法人成立。"),choice(3,"法人須依民法或其他法律規定成立。",true,"正確。第25條採法律保留。"),choice(4,"所有非營利團體都有法人格。",false,"錯誤。非營利性不等於法人格。")],relatedArticles:["gb2-art25"],essayPrompt:"說明團體存在與法人成立的差別。",essayHint:"從法律規定與法人人格分析。",tags:["法人","團體","基金會"],imageUrl,explanation:"法人須依法成立，不能僅以名稱主張。",legalBasis:"民法第25條"},
];
