const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const INHERITANCE_BATCH_3_ARTICLES=[
 {id:"ib3-1168",number:"第1168條",title:"分割遺產的擔保責任",content:"遺產分割後，各繼承人按所得部分，就他繼承人因分割取得遺產，負與出賣人同一擔保責任。",chapter:"遺產分割",villageId:"inheritance"},
 {id:"ib3-1169",number:"第1169條",title:"分割債權的支付能力擔保",content:"遺產分割後，各繼承人按所得部分，擔保他繼承人因分割取得債權之債務人支付能力；未到期或附停止條件債權，以應清償時為準。",chapter:"遺產分割",villageId:"inheritance"},
 {id:"ib3-1170",number:"第1170條",title:"擔保責任人的無資力分擔",content:"依法負擔保責任之繼承人無支付能力時，原則由有請求權人與他繼承人按所得部分比例分擔；因請求權人過失所致者例外。",chapter:"遺產分割",villageId:"inheritance"},
 {id:"ib3-1172",number:"第1172條",title:"繼承人欠款的應繼分扣還",content:"繼承人對被繼承人負債時，遺產分割應按債務數額從該繼承人應繼分扣還。",chapter:"遺產分割",villageId:"inheritance"},
 {id:"ib3-1173",number:"第1173條",title:"特種贈與的歸扣",content:"繼承人因結婚、分居或營業受贈財產，原則將贈與價額加入應繼遺產並由其應繼分扣除；被繼承人反對時例外，價額按贈與時價值計算。",chapter:"遺產分割",villageId:"inheritance"},
];
export const INHERITANCE_BATCH_3_SCENARIOS=[
 {id:"inheritance-031",villageId:"inheritance",title:"分到的機車另有主人",chapter:"遺產分割",difficulty:"hard",story:["三名手足分割遺產，姊姊分到一台機車；分割後，第三人提出證據主張該機車原屬自己。"],question:"依民法第1168條，何者正確？",choices:[c(1,"其他繼承人按所得部分，對姊姊負與出賣人同一的擔保責任。",true,"正確。第1168條針對分割取得遺產設擔保責任。"),c(2,"分割後一律由姊姊獨自承擔，其他人完全無關。",false,"錯誤。法律特設共同繼承人間的擔保責任。"),c(3,"只有實際交付機車的人須負擔保責任。",false,"錯誤。按各繼承人所得部分判斷。"),c(4,"遺產分割不會產生任何擔保責任。",false,"錯誤。第1168條正是分割後的擔保規定。")],relatedArticles:["ib3-1168"],essayPrompt:"說明遺產分割後，繼承人對其他人所分得特定遺產的擔保責任。",essayHint:"分割後、按所得部分、與出賣人同一擔保責任。",tags:["遺產分割","擔保責任"],imageUrl,legalBasis:"民法第1168條"},
 {id:"inheritance-032",villageId:"inheritance",title:"分到父親借出的債權",chapter:"遺產分割",difficulty:"hard",story:["遺產中有亡父借給朋友的到期借據，弟弟分到該債權；分割當日，該朋友已明顯無力還款。"],question:"依民法第1169條，其他繼承人所負擔保主要指向何時的支付能力？",choices:[c(1,"遺產分割時債務人的支付能力。",true,"正確。一般到期債權以遺產分割時為判斷點。"),c(2,"被繼承人借款當天的支付能力。",false,"錯誤。條文不是以借款發生時為準。"),c(3,"弟弟提出請求時任意選擇的一天。",false,"錯誤。法律已有明確判斷時點。"),c(4,"永遠只看債務人十年後的支付能力。",false,"錯誤。只有未到期或附停止條件債權另以應清償時為準。")],relatedArticles:["ib3-1169"],essayPrompt:"比較一般債權與未到期、附停止條件債權的支付能力判斷時點。",essayHint:"分割時；未到期或停止條件則應清償時。",tags:["債權","支付能力"],imageUrl,legalBasis:"民法第1169條"},
 {id:"inheritance-033",villageId:"inheritance",title:"擔保人無力負擔的缺口",chapter:"遺產分割",difficulty:"hard",story:["依遺產分割擔保規定，本應負擔保責任的哥哥已無支付能力；妹妹沒有因自己的疏失造成此結果。"],question:"依民法第1170條，不能償還的部分原則如何處理？",choices:[c(1,"由有請求權的妹妹與其他繼承人按所得部分比例分擔。",true,"正確。條文規範無資力時的風險分配。"),c(2,"妹妹必須一人承受全部缺口。",false,"錯誤。原則是與其他繼承人按所得部分分擔。"),c(3,"由哥哥的債權人當然補足。",false,"錯誤。不是該條所定結果。"),c(4,"無論原因均可向其他繼承人請求分擔。",false,"錯誤。若因有請求權人過失導致不能償還，則不得請求。")],relatedArticles:["ib3-1170"],essayPrompt:"說明分割後擔保責任人無資力時的分擔原則與過失例外。",essayHint:"按所得比例；請求權人過失例外。",tags:["擔保責任","無資力"],imageUrl,legalBasis:"民法第1170條"},
 {id:"inheritance-034",villageId:"inheritance",title:"兒子尚未清償的借款",chapter:"遺產分割",difficulty:"medium",story:["父親生前借給兒子二十萬元，兒子尚未還款即父親過世；手足現在協議分割遺產。"],question:"依民法第1172條，何者正確？",choices:[c(1,"應按債務數額從兒子的應繼分內扣還。",true,"正確。繼承人對被繼承人負債應在分割時扣還。"),c(2,"父親一過世，這筆債務當然消滅。",false,"錯誤。繼承開始不當然免除債務。"),c(3,"只能要求其他手足各自代替兒子償還。",false,"錯誤。條文以兒子應繼分扣還為規則。"),c(4,"遺產分割時不得處理繼承人欠被繼承人的債務。",false,"錯誤。第1172條就是分割時處理規定。")],relatedArticles:["ib3-1172"],essayPrompt:"說明繼承人對被繼承人負債時，遺產分割為何要扣還。",essayHint:"債務數額、應繼分內、分割時。",tags:["應繼分","扣還"],imageUrl,legalBasis:"民法第1172條"},
 {id:"inheritance-035",villageId:"inheritance",title:"父親資助創業的那筆錢",chapter:"遺產分割",difficulty:"hard",story:["父親生前資助女兒開店，未表示免除歸扣；父親過世後，手足開始分割遺產。"],question:"依民法第1173條，何者正確？",choices:[c(1,"創業贈與價額原則加入應繼遺產，並從女兒應繼分扣除，價額按贈與時價值計算。",true,"正確。營業目的的特種贈與適用歸扣規則。"),c(2,"任何生前贈與一律不影響遺產分割。",false,"錯誤。結婚、分居或營業的特種贈與原則應歸扣。"),c(3,"一律按父親死亡當日的市場價值計算。",false,"錯誤。法律明定依贈與時價值。"),c(4,"只要子女受贈就絕對不得例外。",false,"錯誤。被繼承人贈與時反對歸扣時，得不適用。")],relatedArticles:["ib3-1173"],essayPrompt:"說明特種贈與歸扣的要件、例外與價額時點。",essayHint:"結婚、分居、營業；反對意思表示；贈與時價值。",tags:["特種贈與","歸扣"],imageUrl,legalBasis:"民法第1173條"}
];
