const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const INHERITANCE_BATCH_2_ARTICLES=[
 {id:"ib2-1153",number:"第1153條",title:"繼承人對遺產債務的責任",content:"繼承人對被繼承人債務以所得遺產為限負連帶責任；相互間按應繼分比例負擔。",chapter:"繼承效力",villageId:"inheritance"},
 {id:"ib2-1157",number:"第1157條",title:"遺產債權公示催告",content:"法院公告命債權人在一定期限內報明債權；期限不得少於三個月。",chapter:"限定繼承",villageId:"inheritance"},
 {id:"ib2-1158",number:"第1158條",title:"催告期間禁止清償",content:"繼承人在前條一定期限內，不得對任何被繼承人債權人償還債務。",chapter:"限定繼承",villageId:"inheritance"},
 {id:"ib2-1165",number:"第1165條",title:"遺囑定分割方法與禁止分割",content:"遺囑定分割方法時從其所定；遺囑禁止分割遺產效力以十年為限。",chapter:"遺產分割",villageId:"inheritance"},
 {id:"ib2-1166",number:"第1166條",title:"胎兒的遺產應繼分",content:"胎兒為繼承人時，非保留其應繼分不得分割；胎兒分割由其母代理。",chapter:"遺產分割",villageId:"inheritance"},
];
export const INHERITANCE_BATCH_2_SCENARIOS=[
 {id:"inheritance-026",villageId:"inheritance",title:"遺產內的未清貸款",chapter:"繼承效力",difficulty:"hard",story:["父親留下遺產與未清貸款，兩名子女繼承後，銀行向其中一人催收全部債務。"],question:"依民法第1153條，何者正確？",choices:[c(1,"繼承人對外以所得遺產為限負連帶責任，內部原則按應繼分負擔。",true,"正確。條文分別規範外部與內部關係。"),c(2,"銀行只能向每位繼承人各追一半。",false,"錯誤。對外是連帶責任。"),c(3,"繼承人要以自己原有財產無限清償。",false,"錯誤。以因繼承所得遺產為限。"),c(4,"繼承人之間不得按應繼分分擔。",false,"錯誤。內部原則按應繼分比例。")],relatedArticles:["ib2-1153"],essayPrompt:"區分遺產債務的對外責任與繼承人內部分擔。",essayHint:"遺產限度、連帶、應繼分。",tags:["遺產債務","連帶責任"],imageUrl,legalBasis:"民法第1153條"},
 {id:"inheritance-027",villageId:"inheritance",title:"公告尋找遺產債權人",chapter:"限定繼承",difficulty:"medium",story:["繼承人陳報遺產清冊後，希望法院公告請所有債權人在期限內報明債權。"],question:"依民法第1157條，公告期限至少多久？",choices:[c(1,"不得少於三個月。",true,"正確。法律設最低期間。"),c(2,"至少七日。",false,"錯誤。期間不得少於三個月。"),c(3,"至少一個月。",false,"錯誤。低於法定最低期間。"),c(4,"期限完全由繼承人任意決定。",false,"錯誤。由法院公示催告，且有最短期間。")],relatedArticles:["ib2-1157"],essayPrompt:"說明遺產債權公示催告與期間下限。",essayHint:"法院公告、債權人報明、至少三個月。",tags:["遺產清冊","公示催告"],imageUrl,legalBasis:"民法第1157條"},
 {id:"inheritance-028",villageId:"inheritance",title:"催告期間的優先還債",chapter:"限定繼承",difficulty:"hard",story:["法院公告催告債權人的三個月期間尚未結束，一名熟識債權人要求繼承人先拿遺產還他。"],question:"依民法第1158條，何者正確？",choices:[c(1,"繼承人在該期限內不得向任何債權人償還債務。",true,"正確。避免偏頗清償。"),c(2,"熟識債權人可以優先受償。",false,"錯誤。條文禁止向任何債權人清償。"),c(3,"只要債務是真的就可先還。",false,"錯誤。催告期間仍受禁止。"),c(4,"繼承人可自行挑一位先還。",false,"錯誤。法律為全體債權人設保障。")],relatedArticles:["ib2-1158"],essayPrompt:"說明第1158條禁止提前清償的功能。",essayHint:"催告期間、任何債權人、平等保障。",tags:["債權人","清償"],imageUrl,legalBasis:"民法第1158條"},
 {id:"inheritance-029",villageId:"inheritance",title:"遺囑禁止分割祖厝",chapter:"遺產分割",difficulty:"medium",story:["父親遺囑寫明祖厝十年內不得分割，子女想知道限制是否有效。"],question:"依民法第1165條，何者正確？",choices:[c(1,"遺囑禁止分割的效力以十年為限。",true,"正確。條文明定上限。"),c(2,"遺囑禁止分割可以永久有效。",false,"錯誤。最長十年。"),c(3,"遺囑指定分割方法一律無效。",false,"錯誤。原則上從遺囑所定。"),c(4,"遺囑完全不能涉及遺產分割。",false,"錯誤。可定方法或託他人代定。")],relatedArticles:["ib2-1165"],essayPrompt:"說明遺囑對遺產分割方法與禁止分割的效力。",essayHint:"從其所定、十年上限。",tags:["遺囑","遺產分割"],imageUrl,legalBasis:"民法第1165條"},
 {id:"inheritance-030",villageId:"inheritance",title:"尚未出生的繼承人",chapter:"遺產分割",difficulty:"hard",story:["被繼承人過世時，其配偶懷孕，其他繼承人急著分割遺產，卻未替尚未出生的孩子預留份額。"],question:"依民法第1166條，何者正確？",choices:[c(1,"應先保留胎兒應繼分，胎兒分割由母代理。",true,"正確。條文特別保障胎兒繼承。"),c(2,"胎兒出生前絕不能考慮其繼承。",false,"錯誤。法律要求保留應繼分。"),c(3,"其他繼承人可先分完，出生後再說。",false,"錯誤。未保留不得分割。"),c(4,"胎兒分割一律由祖父母代理。",false,"錯誤。由其母代理。")],relatedArticles:["ib2-1166"],essayPrompt:"說明胎兒為繼承人時的遺產分割限制與代理人。",essayHint:"保留應繼分、母代理。",tags:["胎兒","遺產分割"],imageUrl,legalBasis:"民法第1166條"}
];
