const imageUrl="https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/obligation-016-C2jdVdwzMe8GTXf5KRNJqk.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const INHERITANCE_BATCH_1_ARTICLES=[
 {id:"ib1-1138",number:"第1138條",title:"法定繼承人順位",content:"遺產繼承人除配偶外，依序為直系血親卑親屬、父母、兄弟姊妹、祖父母。",chapter:"法定繼承",villageId:"inheritance"},
 {id:"ib1-1140",number:"第1140條",title:"代位繼承",content:"第一順位繼承人先死亡或喪失繼承權時，由其直系血親卑親屬代位繼承其應繼分。",chapter:"法定繼承",villageId:"inheritance"},
 {id:"ib1-1141",number:"第1141條",title:"同順位平均繼承",content:"同一順序繼承人有數人時，按人數平均繼承，但法律另有規定者除外。",chapter:"法定繼承",villageId:"inheritance"},
 {id:"ib1-1151",number:"第1151條",title:"遺產公同共有",content:"繼承人有數人時，分割遺產前，各繼承人對遺產全部為公同共有。",chapter:"遺產分割",villageId:"inheritance"},
 {id:"ib1-1152",number:"第1152條",title:"互推遺產管理人",content:"公同共有的遺產，得由繼承人中互推一人管理。",chapter:"遺產分割",villageId:"inheritance"},
];
export const INHERITANCE_BATCH_1_SCENARIOS=[
 {id:"inheritance-021",villageId:"inheritance",title:"有子女時的兄弟姊妹",chapter:"法定繼承",difficulty:"easy",story:["老王過世，留有配偶、一名女兒與兩名兄弟姊妹，未留遺囑。"],question:"依民法第1138條，何者正確？",choices:[c(1,"女兒是第一順位，兄弟姊妹不得越過她繼承。",true,"正確。直系血親卑親屬優先於兄弟姊妹。"),c(2,"兄弟姊妹與女兒一定平均繼承。",false,"錯誤。繼承順位有先後。"),c(3,"兄弟姊妹一定優先於子女。",false,"錯誤。子女為第一順位。"),c(4,"只要有兄弟姊妹，配偶完全不能繼承。",false,"錯誤。配偶依法與各順序繼承人共同繼承。")],relatedArticles:["ib1-1138"],essayPrompt:"列出配偶外的法定繼承人順位。",essayHint:"直系卑親屬、父母、兄弟姊妹、祖父母。",tags:["繼承順位","子女"],imageUrl,legalBasis:"民法第1138條"},
 {id:"inheritance-022",villageId:"inheritance",title:"先亡母親留下的孫女",chapter:"法定繼承",difficulty:"medium",story:["阿嬤過世前，其女兒已先死亡，該女兒留下女兒小芳。"],question:"依民法第1140條，小芳的地位為何？",choices:[c(1,"小芳可代位繼承母親原本的應繼分。",true,"正確。第一順位先亡者的直系卑親屬可代位。"),c(2,"小芳必須等所有長輩都放棄才可繼承。",false,"錯誤。符合代位繼承即直接代位。"),c(3,"孫女永遠不是繼承人。",false,"錯誤。代位繼承是法定例外。"),c(4,"小芳可以繼承比母親更多的份額。",false,"錯誤。代位的是母親應繼分。")],relatedArticles:["ib1-1140"],essayPrompt:"說明代位繼承的要件與效果。",essayHint:"第一順位、先死亡或喪失資格、直系卑親屬、應繼分。",tags:["代位繼承","孫子女"],imageUrl,legalBasis:"民法第1140條"},
 {id:"inheritance-023",villageId:"inheritance",title:"同順位的兩名子女",chapter:"法定繼承",difficulty:"easy",story:["被繼承人未婚，留下兩名子女，沒有遺囑，也沒有其他特別法律規定。"],question:"依民法第1141條，兩名子女應如何繼承？",choices:[c(1,"同順位按人數平均，各得一半。",true,"正確。同順序數人原則平均。"),c(2,"年長子女必然多得一倍。",false,"錯誤。法律不採長幼差別。"),c(3,"收入較低者當然取得全部。",false,"錯誤。第1141條原則按人數。"),c(4,"兩人必須先抽籤才能繼承。",false,"錯誤。應繼分原則平均。")],relatedArticles:["ib1-1141"],essayPrompt:"說明同順位繼承人數人時的基本分配原則。",essayHint:"按人數平均與法律另有規定例外。",tags:["應繼分","平均繼承"],imageUrl,legalBasis:"民法第1141條"},
 {id:"inheritance-024",villageId:"inheritance",title:"分割前的遺產房屋",chapter:"遺產分割",difficulty:"hard",story:["三名繼承人尚未分割遺產，其中一人主張自己持有三分之一，便可單獨出售整棟遺產房屋。"],question:"依民法第1151條，何者正確？",choices:[c(1,"分割前遺產全部屬全體繼承人公同共有，不能視為一人單獨財產。",true,"正確。遺產分割前為公同共有。"),c(2,"每人可自行出售整棟房屋。",false,"錯誤。沒有單獨處分全體遺產的權限。"),c(3,"遺產在死亡時即自動分割。",false,"錯誤。分割前仍屬公同共有。"),c(4,"只有最年長繼承人取得所有權。",false,"錯誤。法律不採此規則。")],relatedArticles:["ib1-1151"],essayPrompt:"說明遺產分割前的公同共有關係。",essayHint:"繼承人有數人、遺產全部、公同共有、分割前。",tags:["公同共有","遺產房屋"],imageUrl,legalBasis:"民法第1151條"},
 {id:"inheritance-025",villageId:"inheritance",title:"互推一人管理遺產",chapter:"遺產分割",difficulty:"medium",story:["多名繼承人尚未分割遺產，空置房屋需要收租、繳稅與基本維護。"],question:"依民法第1152條，何者正確？",choices:[c(1,"繼承人得互推一人管理公同共有遺產。",true,"正確。第1152條明定互推管理人。"),c(2,"遺產在分割前絕對不能管理。",false,"錯誤。可互推管理人。"),c(3,"法院一定要先指定才可管理。",false,"錯誤。條文允許繼承人互推。"),c(4,"只有最大應繼分者可管理。",false,"錯誤。規定是互推一人。")],relatedArticles:["ib1-1152"],essayPrompt:"說明繼承人共同管理分割前遺產的方式。",essayHint:"公同共有與互推一人管理。",tags:["遺產管理","公同共有"],imageUrl,legalBasis:"民法第1152條"}
];
