const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const INHERITANCE_BATCH_4_ARTICLES=[
 {id:"ib4-1174",number:"第1174條",title:"拋棄繼承的程序",content:"繼承人得拋棄繼承；知悉得繼承起三個月內，以書面向法院為之，並書面通知因拋棄而應繼承之人。",chapter:"拋棄繼承",villageId:"inheritance"},
 {id:"ib4-1175",number:"第1175條",title:"拋棄繼承的溯及效力",content:"繼承之拋棄，溯及於繼承開始時發生效力。",chapter:"拋棄繼承",villageId:"inheritance"},
 {id:"ib4-1176",number:"第1176條",title:"拋棄繼承的應繼分歸屬",content:"第一順序繼承人拋棄時，其應繼分歸其他同為繼承之人；其他順位、配偶與後順位繼承另依條文規定處理。",chapter:"拋棄繼承",villageId:"inheritance"},
 {id:"ib4-1177",number:"第1177條",title:"繼承人不明時的遺產管理",content:"繼承開始時繼承人有無不明，親屬會議應於一個月內選定遺產管理人，並向法院報明。",chapter:"遺產管理",villageId:"inheritance"},
 {id:"ib4-1179",number:"第1179條",title:"遺產管理人的職務與清償順序",content:"遺產管理人應編製清冊、保存遺產、催告債權人與受遺贈人、清償債權或交付遺贈物並移交；清冊三個月內編製，債權清償先於遺贈物交付。",chapter:"遺產管理",villageId:"inheritance"},
];
export const INHERITANCE_BATCH_4_SCENARIOS=[
 {id:"inheritance-036",villageId:"inheritance",title:"群組裡的拋棄繼承",chapter:"拋棄繼承",difficulty:"medium",story:["表哥得知自己可能繼承叔叔遺產後，在家族群組留言『我不要繼承』，但沒有寄書面給法院。"],question:"依民法第1174條，要合法拋棄繼承，何者正確？",choices:[c(1,"應自知悉得繼承起三個月內，以書面向法院為之。",true,"正確。群組留言不是條文所定程序。"),c(2,"只要在群組公開聲明即可。",false,"錯誤。法律要求書面向法院。"),c(3,"可在任何時間以口頭向親友表示。",false,"錯誤。有限期與書面程序。"),c(4,"只需通知債權人，不必通知法院。",false,"錯誤。應向法院為書面拋棄。")],relatedArticles:["ib4-1174"],essayPrompt:"說明拋棄繼承的期間、形式與通知要求。",essayHint:"知悉得繼承起三個月、書面向法院、通知後手繼承人。",tags:["拋棄繼承","法院"],imageUrl,legalBasis:"民法第1174條"},
 {id:"inheritance-037",villageId:"inheritance",title:"拋棄後回到繼承開始日",chapter:"拋棄繼承",difficulty:"medium",story:["阿明依法向法院拋棄父親的繼承後，妹妹問：阿明是從法院收件日才不算繼承人嗎？"],question:"依民法第1175條，何者正確？",choices:[c(1,"拋棄繼承溯及於繼承開始時發生效力。",true,"正確。法律明定溯及時點。"),c(2,"僅從法院收件日才發生效力。",false,"錯誤。不是條文規定的時點。"),c(3,"須等遺產分割完才有效。",false,"錯誤。效力不以分割完成為要件。"),c(4,"要等其他繼承人同意才會生效。",false,"錯誤。條文未以他人同意為要件。")],relatedArticles:["ib4-1175"],essayPrompt:"說明合法拋棄繼承的溯及效力與意義。",essayHint:"溯及、繼承開始時。",tags:["拋棄繼承","溯及效力"],imageUrl,legalBasis:"民法第1175條"},
 {id:"inheritance-038",villageId:"inheritance",title:"拋棄的子女那一份",chapter:"拋棄繼承",difficulty:"hard",story:["父親過世時沒有配偶，僅有兩名子女共同繼承；其中一名子女合法拋棄繼承，另一名子女仍願意繼承。"],question:"依民法第1176條第一項，拋棄子女的應繼分原則歸誰？",choices:[c(1,"歸屬於另一名同為繼承的子女。",true,"正確。本題僅有兩名第一順序子女共同繼承，拋棄者的份額歸另一名同為繼承人。"),c(2,"當然歸國庫。",false,"錯誤。尚有其他同為繼承的子女。"),c(3,"永久保留在遺產中，無人取得。",false,"錯誤。法律對拋棄後應繼分另定歸屬。"),c(4,"由拋棄人日後任意指定受領人。",false,"錯誤。應繼分歸屬依法律規定，不由拋棄人任意指定。")],relatedArticles:["ib4-1176"],essayPrompt:"說明第一順序繼承人拋棄時應繼分的歸屬，並注意配偶、不同順位與全體近親等子女拋棄時另有規則。",essayHint:"其他同為繼承之人；不同身分與順位另依條文判斷。",tags:["應繼分","第一順序"],imageUrl,legalBasis:"民法第1176條"},
 {id:"inheritance-039",villageId:"inheritance",title:"找不到繼承人的遺產",chapter:"遺產管理",difficulty:"hard",story:["獨居的林先生過世後，鄰里與親屬無法確認是否有子女或其他繼承人，遺產卻需要有人保存管理。"],question:"依民法第1177條，親屬會議原則上應如何處理？",choices:[c(1,"於一個月內選定遺產管理人，並將繼承開始與選定事由向法院報明。",true,"正確。這是繼承人有無不明時的法定處理。"),c(2,"立即由鄰居自行分配遺產。",false,"錯誤。繼承人不明不能自行分配。"),c(3,"等十年後再考慮管理。",false,"錯誤。法律要求一個月內選定管理人。"),c(4,"只要上網公告即可，不必向法院報明。",false,"錯誤。尚須向法院報明。")],relatedArticles:["ib4-1177"],essayPrompt:"說明繼承人有無不明時，親屬會議選任遺產管理人的期限與報明事項。",essayHint:"一個月、遺產管理人、向法院報明。",tags:["遺產管理","繼承人不明"],imageUrl,legalBasis:"民法第1177條"},
 {id:"inheritance-040",villageId:"inheritance",title:"遺產管理人先還誰",chapter:"遺產管理",difficulty:"hard",story:["繼承人不明，遺產管理人已收到債權人與受遺贈人的請求，遺產現金不足以同時滿足全部要求。"],question:"依民法第1179條，何者正確？",choices:[c(1,"應先清償債權，再交付遺贈物。",true,"正確。條文明定債權清償先於遺贈物交付。"),c(2,"應先交付受遺贈人，再看有無餘額還債。",false,"錯誤。順序相反。"),c(3,"遺產管理人完全不必編製清冊。",false,"錯誤。就職後三個月內應編製清冊。"),c(4,"任何人要求都可先隨意變賣遺產。",false,"錯誤。為清償或交付必要時，須經親屬會議同意才得變賣。")],relatedArticles:["ib4-1179"],essayPrompt:"說明遺產管理人的核心職務與債權清償、遺贈物交付的先後順序。",essayHint:"清冊、保存、催告、先債權後遺贈。",tags:["遺產管理","受遺贈人"],imageUrl,legalBasis:"民法第1179條"}
];
