export const NEW_FAMILY_SCENARIOS = [
  {
    id: "family-017",
    villageId: "family",
    title: "夫妻住所的協議與推定",
    chapter: "第四章 親屬",
    difficulty: "medium" as const,
    story: [
      "小張和小美結婚後，雙方對於未來要住在台北娘家附近還是高雄老家產生嚴重爭執。",
      "小張認為夫權至上，妻子應該跟隨丈夫的住所居住；小美則認為男女平等，雙方意見不一致時應該訴諸法律。",
      "兩人因此分居，甚至互控對方惡意遺棄與不履行同居義務。",
    ],
    question: "根據民法規定，夫妻之住所應如何決定？若協議不成時如何處理？",
    choices: [
      { id: 1, text: "一律以丈夫的戶籍地為夫妻法定住所", isCorrect: false, explanation: "民法早已刪除夫家住所優先之規定，改採雙方協議。" },
      { id: 2, text: "由雙方共同協議之；未為協議或協議不成時，得聲請法院定之", isCorrect: true, explanation: "根據民法第 1002 條，夫妻之住所，由雙方共同協議之；未為協議或協議不成時，得聲請法院定之。法院裁定前以共同戶籍地推定。" },
      { id: 3, text: "由民政局抽籤決定", isCorrect: false, explanation: "法律無抽籤決定住所之規定。" },
      { id: 4, text: "各自隨自己父母居住即可，不需共同協議", isCorrect: false, explanation: "夫妻互負同居義務，住所應由雙方協議。" },
    ],
    explanation: "民法第 1002 條落實男女平等原則，明定夫妻住所由雙方共同協議；若協議不成，可聲請法院定之，在法院裁定前暫以共同戶籍地推定。",
    legalBasis: "民法第 1002 條（夫妻住所之決定）",
    relatedArticles: ["art1001", "art1002"],
    essayPrompt: "請論述我國親屬法中夫妻住所決定權之演變與平權原則之落實。",
    essayHint: "可從民法第 1002 條修正歷程切入，討論從傳統夫權支配轉為夫妻平等協議與法院裁判之法理轉變。",
    tags: ["夫妻住所", "同居義務", "親屬法"],
    imageUrl: "images/h00mgsz-e33cf4ec4604.webp",
  },
  {
    id: "family-018",
    villageId: "family",
    title: "日常家務的互為代理權",
    chapter: "第四章 親屬",
    difficulty: "medium" as const,
    story: [
      "太太平日負責處理家中大小採買與日常水電維修費用。",
      "某日，太太未事先告知先生，擅自以家庭日常所需名義，向社區附近的電器行購買了一臺新冰箱，並登記由先生的帳戶付款。",
      "先生回家後大發雷霆，認為這筆開銷太大，主張太太無權代表他簽署買賣契約。",
    ],
    question: "關於夫妻於日常家務之代理權，下列敘述何者正確？",
    choices: [
      { id: 1, text: "夫妻任何一方均不得代表他方簽署任何契約", isCorrect: false, explanation: "法律明定日常家務互為代理權。" },
      { id: 2, text: "夫妻於日常家務，互為代理人", isCorrect: true, explanation: "根據民法第 1003 條第 1 項，夫妻於日常家務，互為代理人。夫妻之一方濫用代理權時，他方得限制之，但不得對抗善意第三人。" },
      { id: 3, text: "只有丈夫可以代表家庭對外購物，妻子不行", isCorrect: false, explanation: "現行法採夫妻平等互為代理。" },
      { id: 4, text: "日常家務買賣金額超過一千元即屬無效", isCorrect: false, explanation: "金額高低視日常家務範圍認定，非以一千元為限。" },
    ],
    explanation: "民法第 1003 條規定夫妻於日常家務互為代理人。購買冰箱屬於日常家電採購，原則上對配偶發生效力，保障交易安全。",
    legalBasis: "民法第 1003 條（日常家務代理權）",
    relatedArticles: ["art1003"],
    essayPrompt: "請說明日常家務代理權的範圍與善意第三人保護之法理基礎。",
    essayHint: "可從民法第 1003 條出發，討論日常家務之認定標準（家庭經濟狀況、生活水準、地區習俗）與交易安全之維護。",
    tags: ["日常家務", "代理權", "夫妻權利"],
    imageUrl: "images/lfwdlrh-1609d1d8dca8.webp",
  },
  {
    id: "family-019",
    villageId: "family",
    title: "婚生推定與否認之訴期限",
    chapter: "第四章 親屬",
    difficulty: "hard" as const,
    story: [
      "阿強與小花在婚姻關係存續中生下一子。",
      "數年後，阿強因基因檢測意外發現兒子並非自己的親生骨肉，憤而向法院提起否認子女之訴。",
      "此時距離阿強確知此事已經過了 3 年之久，小花主張阿強超過法定期限，訴訟不合法。",
    ],
    question: "依民法規定，夫妻之一方提起否認子女之訴的法定期限為多久？",
    choices: [
      { id: 1, text: "自知悉子女非為婚生子女之時起 2 年內", isCorrect: true, explanation: "根據民法第 1063 條第 3 項，否認之訴應自夫妻之一方自知悉該子女非為婚生子女之時起 2 年內為之。" },
      { id: 2, text: "自子女出生之日起 10 年內隨時可提", isCorrect: false, explanation: "法律規定期限為知悉後 2 年，非出生後 10 年。" },
      { id: 3, text: "沒有時間限制，隨時都能提起", isCorrect: false, explanation: "為了維護身分安定，否認之訴設有除斥期間限制。" },
      { id: 4, text: "必須在子女滿 18 歲前提出", isCorrect: false, explanation: "期限是以知悉時起算 2 年，與成年與否無絕對關聯。" },
    ],
    explanation: "民法第 1063 條規定，妻之受胎係在婚姻關係存續中者推定為婚生子女。若要提起否認之訴，須自知悉非婚生子女之時起 2 年內為之，逾期即不得提起。",
    legalBasis: "民法第 1063 條（婚生推定與否認之訴）",
    relatedArticles: ["art1052", "art1063"],
    essayPrompt: "請論述婚生推定制度的立法目的與否認子女之訴除斥期間之正當性。",
    essayHint: "可從民法第 1063 條與大法官解釋（如釋字第 587 號等）切入，討論身分安定與真實血統主義之衡平。",
    tags: ["婚生推定", "否認子女", "親屬訴訟"],
    imageUrl: "images/im3rjfd-6216b2954a2c.webp",
  },
  {
    id: "family-020",
    villageId: "family",
    title: "合意終止收養的法院認可",
    chapter: "第四章 親屬",
    difficulty: "medium" as const,
    story: [
      "多年前王大伯依法收養了一名未成年養子小明。",
      "近年來雙方因理念不合，且小明已漸漸成年，雙方達成合意決定終止收養關係。",
      "王大伯認為既然雙方都同意，只要簽個協議書到戶政事務所辦理登記就大功告成了。",
    ],
    question: "養子女若為未成年人，終止收養關係時除了雙方合意書面外，還需要完成什麼法定程序？",
    choices: [
      { id: 1, text: "只要雙方簽約即可，不需任何其他手續", isCorrect: false, explanation: "未成年人終止收養必須向法院聲請認可。" },
      { id: 2, text: "應向法院聲請認可，自法院認可裁定確定時發生效力", isCorrect: true, explanation: "根據民法第 1080 條第 2 項與第 4 項，養父母與養子女之關係得合意終止，但養子女為未成年人者，應向法院聲請認可，自裁定確定時發生效力。" },
      { id: 3, text: "必須經過宗族長老會議同意並公告三個月", isCorrect: false, explanation: "法律無宗族公告終止收養之規定。" },
      { id: 4, text: "由檢察官直接裁決終止", isCorrect: false, explanation: "終止收養認可管轄權在法院而非檢察官。" },
    ],
    explanation: "民法第 1080 條規定，終止收養應以書面為之；若養子女為未成年人，更須向法院聲請認可，並以法院裁定確定時發生效力，以落實未成年子女最佳利益保障。",
    legalBasis: "民法第 1080 條（終止收養關係）",
    relatedArticles: ["art1075", "art1080"],
    essayPrompt: "請說明收養關係終止的要件，並比較成年人與未成年人終止收養程序之差異。",
    essayHint: "可從民法第 1080 條出發，討論未成年人終止收養須經法院認可及審酌最佳利益原則之要求。",
    tags: ["收養", "終止收養", "法院認可"],
    imageUrl: "images/y3afpcr-e32ddb130efb.webp",
  },
];
