export const NEW_GENERAL_SCENARIOS = [
  {
    id: "general-017",
    villageId: "general",
    title: "失蹤人的財產危機",
    chapter: "第一章 總則",
    difficulty: "medium" as const,
    story: [
      "老張在一次山區健行中意外失蹤，音訊全無，家屬焦急萬分。",
      "在法院尚未宣告老張死亡之前，家屬面臨老張名下銀行的房貸與租金繳納問題。",
      "大兒子認為既然失蹤了，可以直接把房子賣掉來還債。",
      "二兒子則認為在未受死亡宣告前，財產不能隨意處分，必須依法妥善管理。",
    ],
    question: "根據民法規定，失蹤人失蹤後，未受死亡宣告前，其財產之管理應依何種法律規定處理？",
    choices: [
      { id: 1, text: "由家屬自行決定拍賣變現", isCorrect: false, explanation: "失蹤人財產不能由家屬任意處分，須依法定程序管理。" },
      { id: 2, text: "依家事事件法之規定處理", isCorrect: true, explanation: "根據民法第 10 條規定，失蹤人失蹤後，未受死亡宣告前，其財產之管理，除其他法律另有規定者外，依家事事件法之規定。" },
      { id: 3, text: "視同死亡，直接進行遺產繼承", isCorrect: false, explanation: "未經法院死亡宣告前，不得視為死亡或直接進行繼承。" },
      { id: 4, text: "由檢察官直接沒收並代為清算", isCorrect: false, explanation: "檢察官並無直接沒收或清算失蹤人財產的權限。" },
    ],
    explanation: "民法第 10 條明定，失蹤人失蹤後，未受死亡宣告前，其財產之管理依家事事件法規定辦理，以保障失蹤人權益並兼顧利害關係人利益。",
    legalBasis: "民法第 10 條（失蹤人之財產管理）",
    relatedArticles: ["art10"],
    essayPrompt: "請說明失蹤宣告與死亡宣告的差別，以及失蹤人財產管理制度的立法目的。",
    essayHint: "可從民法失蹤宣告與家事事件法財產管理程序切入，討論立法上如何平衡失蹤人重返社會的可能與家屬財產保全的需求。",
    tags: ["失蹤", "財產管理", "家事事件法"],
    imageUrl: "images/pb1okly-a09981f7d38a.webp",
  },
  {
    id: "general-018",
    villageId: "general",
    title: "受輔助宣告者的契約界限",
    chapter: "第一章 總則",
    difficulty: "hard" as const,
    story: [
      "小華因精神障礙，經法院依法為「輔助宣告」。",
      "某日，小華未經輔助人同意，擅自將名下的一輛汽車以低價賣給二手車商。",
      "車商明知小華受輔助宣告，仍迅速完成過戶手續。",
      "輔助人事後得知，認為該買賣契約無效，要求車商返還車輛。",
    ],
    question: "受輔助宣告之人未經輔助人同意而為汽車買賣，其法律效力為何？",
    choices: [
      { id: 1, text: "當然無效，任何人皆可主張", isCorrect: false, explanation: "受輔助宣告人並非無行為能力人，其法律行為非當然無效。" },
      { id: 2, text: "有效契約，車商取得合法所有權", isCorrect: false, explanation: "法律規定重要財產處分應經輔助人同意，未經同意非當然有效。" },
      { id: 3, text: "效力未定，須經輔助人承認始生效力", isCorrect: true, explanation: "根據民法第 15-2 條，受輔助宣告人為汽車等重要財產之處分、買賣，應經輔助人同意；未經同意者，準用限制行為能力人之規定，屬於效力未定。" },
      { id: 4, text: "得由車商單方撤銷契約", isCorrect: false, explanation: "撤銷權主要保障受保護人及其輔助人，車商不得任意主張撤銷。" },
    ],
    explanation: "民法第 15-2 條規定，受輔助宣告人為重要財產之處分、買賣時，應經輔助人同意。未經同意者，其效力未定，輔助人事後得拒絕承認。",
    legalBasis: "民法第 15-2 條（受輔助宣告人之行為能力限制）",
    relatedArticles: ["art14", "art15-2"],
    essayPrompt: "請比較無行為能力人、限制行為能力人與受輔助宣告人在法律行為效力上的差異。",
    essayHint: "可從民法第 13 條（無行為與限制行為能力）、第 14 條與第 15-2 條（受輔助宣告與應經同意之行為）出發，分析保護程度與交易安全的平衡。",
    tags: ["輔助宣告", "行為能力", "效力未定"],
    imageUrl: "images/lyxwbml-17a78ca04705.webp",
  },
  {
    id: "general-019",
    villageId: "general",
    title: "人格權受侵害的救濟",
    chapter: "第一章 總則",
    difficulty: "medium" as const,
    story: [
      "鄰居老王未經同意，擅自在大樓公告欄張貼張小姐的照片，並加註不實的毀謗文字。",
      "張小姐發現後精神受到嚴重打擊，憤而向法院提起訴訟。",
      "張小姐不僅要求老王立刻撕毀公告、防止再次張貼，還要求老王賠償精神慰撫金。",
      "老王抗辯稱：『照片是我拍的，我有權利張貼！』",
    ],
    question: "關於人格權受侵害時的法律救濟，下列敘述何者正確？",
    choices: [
      { id: 1, text: "人格權受侵害時僅能請求金錢賠償，不得請求除去侵害", isCorrect: false, explanation: "人格權受侵害時，首要可請求法院除去或防止侵害。" },
      { id: 2, text: "得請求法院除去其侵害或防止之，且以法律有特別規定者為限始得請求慰撫金", isCorrect: true, explanation: "根據民法第 18 條，人格權受侵害時，得請求除去其侵害或防止之；至於損害賠償或慰撫金，以法律有特別規定者為限（如民法第 195 條）。" },
      { id: 3, text: "任何人只要覺得不開心即可直接沒收對方的相機", isCorrect: false, explanation: "私力救濟原則上不被允許，必須透過法律途徑解決。" },
      { id: 4, text: "人格權侵害超過一年即永久消滅，不得起訴", isCorrect: false, explanation: "人格權受侵害的除去請求權與侵權行為損害賠償時效各有規定，並非一律一年消滅。" },
    ],
    explanation: "民法第 18 條規定，人格權受侵害時，得請求法院除去其侵害，有受侵害之虞時得請求防止；但請求損害賠償或慰撫金，則以法律有特別規定者為限。",
    legalBasis: "民法第 18 條（人格權之保護）",
    relatedArticles: ["art18"],
    essayPrompt: "請論述人格權保護與言論自由之間的界線，以及民法上的救濟方法。",
    essayHint: "可從民法第 18 條（人格權保護）、第 195 條（非財產上損害賠償）與憲法保障言論自由之衡量標準切入。",
    tags: ["人格權", "除去侵害", "慰撫金"],
    imageUrl: "images/voesgxj-0ae4d8fbf6b0.webp",
  },
  {
    id: "general-020",
    villageId: "general",
    title: "附條件的贈與承諾",
    chapter: "第一章 總則",
    difficulty: "medium" as const,
    story: [
      "阿伯向孫子小明承諾：『如果你今年暑假順利考取律師證照，我就把名下一間套房贈與給你。』",
      "小明大受鼓舞，努力備考並順利於同年八月放榜上榜。",
      "正當小明向阿伯要求過戶房屋時，阿伯卻因其他家庭因素反悔，主張當初只是隨口說說，契約並未生效。",
    ],
    question: "阿伯與小明之間的贈與承諾，在民法上屬於何種法律行為？",
    choices: [
      { id: 1, text: "附解除條件之法律行為，條件成就時失其效力", isCorrect: false, explanation: "考取證照是使贈與生效的條件，屬於停止條件而非解除條件。" },
      { id: 2, text: "附停止條件之法律行為，於條件成就時發生效力", isCorrect: true, explanation: "根據民法第 99 條第 1 項，附停止條件之法律行為，於條件成就時，發生效力。小明考取證照條件成就，贈與契約生效。" },
      { id: 3, text: "無效之法律行為，因為未經公證", isCorrect: false, explanation: "附條件的口頭或書面約定在符合條件時即生效力，非因未公證而當然無效。" },
      { id: 4, text: "單純之道德義務，完全沒有法律拘束力", isCorrect: false, explanation: "當事人雙方意思表示一致且附有停止條件時，具備法律拘束力。" },
    ],
    explanation: "民法第 99 條第 1 項規定，附停止條件之法律行為，於條件成就時，發生效力。小明既已考取證照，停止條件已成就，阿伯即應依約履行贈與義務。",
    legalBasis: "民法第 99 條（條件之效力）",
    relatedArticles: ["art99"],
    essayPrompt: "請說明附停止條件與附解除條件法律行為的異同與法律效果。",
    essayHint: "可從民法第 99 條出發，比較條件成就前後對法律行為效力之影響（停止條件成就生效；解除條件成就失其效力）。",
    tags: ["條件", "法律行為", "停止條件"],
    imageUrl: "images/zhnicie-f43bc1a9a9e0.webp",
  },
];
