export const NEW_INHERITANCE_SCENARIOS = [
  {
    id: "inheritance-017",
    villageId: "inheritance",
    title: "繼承權被侵害的回復請求權",
    chapter: "第五章 繼承",
    difficulty: "hard" as const,
    story: [
      "老李過世後留下大筆遺產，次子長年在外地工作。",
      "大兒子利用弟弟不在的機會，隱瞞事實偽造文書，獨占了全部的遺產並辦理所有權移轉。",
      "多年後次子偶然得知真相，憤而向大兒子主張返還應繼分。",
      "大兒子抗辯說事情已經過了很久，弟弟早已喪失請求權。",
    ],
    question: "根據民法規定，繼承權被侵害時，被害人之回復請求權的時效期間為何？",
    choices: [
      { id: 1, text: "自知悉被侵害之日起 2 年內，或自繼承開始時起逾 10 年者消滅", isCorrect: true, explanation: "根據民法第 1146 條第 2 項，回復請求權自知悉被侵害之日起 2 年內不行使而消滅；自繼承開始時起逾 10 年者亦同。" },
      { id: 2, text: "請求權消滅時效一律為 15 年，無其他限制", isCorrect: false, explanation: "繼承回復請求權有特別短期時效（2年與10年）。" },
      { id: 3, text: "只要發現侵害，終身皆可隨時起訴索回", isCorrect: false, explanation: "受 2 年及 10 年除斥期間或消滅時效雙重限制。" },
      { id: 4, text: "繼承權一旦被侵害即永久喪失，不得回復", isCorrect: false, explanation: "法律明定可在法定期限內行使繼承回復請求權。" },
    ],
    explanation: "民法第 1146 條規定，繼承權被侵害時得請求回復之。該請求權具有雙重時效限制：自知悉侵害時起 2 年，或自繼承開始時起 10 年，以維護交易安全與繼承秩序。",
    legalBasis: "民法第 1146 條（繼承回復請求權）",
    relatedArticles: ["art1138", "art1146"],
    essayPrompt: "請論述繼承回復請求權與個別物上請求權之關係與競合問題。",
    essayHint: "可從民法第 1146 條與釋字第 437 號解釋出發，討論繼承回復請求權之性質及其與第 767 條所有物返還請求權之適用範圍。",
    tags: ["繼承回復", "繼承權侵害", "時效期間"],
    imageUrl: "images/fyuxgft-ceeb2536e1d7.webp",
  },
  {
    id: "inheritance-018",
    villageId: "inheritance",
    title: "結婚分居或營業之特種贈與歸扣",
    chapter: "第五章 繼承",
    difficulty: "hard" as const,
    story: [
      "老王生前育有三名子女。大兒子在結婚時，老王曾贈與他 200 萬元作為創業基金與結婚基金。",
      "其餘兩位子女在生前未受特別贈與。",
      "老王過世後留下 1,000 萬元遺產，在進行遺產分割時，其他子女要求將大兒子生前受贈的 200 萬元加入遺產中計算。",
    ],
    question: "關於繼承人於繼承開始前受有財產贈與之歸扣，下列敘述何者正確？",
    choices: [
      { id: 1, text: "生前贈與一律不計入，全部歸受贈人所有", isCorrect: false, explanation: "結婚、分居或營業之特種贈與依法應予歸扣。" },
      { id: 2, text: "因結婚、分居或營業受有財產贈與者，應將該贈與價額加入應繼遺產中並於分割時扣除", isCorrect: true, explanation: "根據民法第 1173 條，繼承人中有在繼承開始前因結婚、分居或營業，已從被繼承人受有財產之贈與者，應將該贈與價額加入繼承開始時被繼承人所有之財產中為應繼遺產，並於分割時由該繼承人之應繼分中扣除。" },
      { id: 3, text: "所有生前贈與均須強制平均扣除，不問贈與名目", isCorrect: false, explanation: "僅限結婚、分居或營業之特種贈與且無反對意思表示者。" },
      { id: 4, text: "歸扣金額應以繼承開始時之通貨膨脹指數重新折算", isCorrect: false, explanation: "法條明定依「贈與時」之價值計算。" },
    ],
    explanation: "民法第 1173 條規範「歸扣」制度，旨在追求繼承人間實質公平。被繼承人生前因結婚、分居或營業給予特定繼承人的財產，應加入應繼遺產計算並自其應繼分中扣除。",
    legalBasis: "民法第 1173 條 (特種贈與之歸扣)",
    relatedArticles: ["art1141", "art1173"],
    essayPrompt: "請說明遺產繼承中「歸扣」制度的立法目的與計算方法。",
    essayHint: "可從民法第 1173 條出發，討論特種贈與（結婚、分居、營業）之範圍、價值計算時點（贈與時）及與特留分之互動關係。",
    tags: ["歸扣", "特種贈與", "應繼分"],
    imageUrl: "images/imywgmg-719dd61a26d8.webp",
  },
  {
    id: "inheritance-019",
    villageId: "inheritance",
    title: "未指定遺囑執行人的選定程序",
    chapter: "第五章 繼承",
    difficulty: "medium" as const,
    story: [
      "老張生前預立了一份合法有效的自書遺囑，妥善交代了各項遺產分配與遺贈事宜。",
      "但在遺囑中卻漏未指定「遺囑執行人」，也未委託他人代為指定。",
      "老張過世後，繼承人與受遺贈人為了如何執行遺囑內容爭執不下，不知該由誰來負責處理。",
    ],
    question: "遺囑未指定遺囑執行人，並未委託他人指定者，得由誰選定或指定？",
    choices: [
      { id: 1, text: "由檢察官直接指派警員執行", isCorrect: false, explanation: "檢察官不直接指派，法律規定由親屬會議選定或法院指定。" },
      { id: 2, text: "得由親屬會議選定之；不能由親屬會議選定時，得由利害關係人聲請法院指定之", isCorrect: true, explanation: "根據民法第 1211 條，遺囑未指定遺囑執行人，並未委託他人指定者，得由親屬會議選定之；不能由親屬會議選定時，得由利害關係人聲請法院指定之。" },
      { id: 3, text: "遺囑直接自動失效，改依法定繼承辦理", isCorrect: false, explanation: "遺囑有效但缺執行人時，依法補選指定即可，不致遺囑無效。" },
      { id: 4, text: "由長子一人當然擔任遺囑執行人", isCorrect: false, explanation: "長子無當然法定執行人地位，須依親屬會議或法院指定。" },
    ],
    explanation: "民法第 1211 條規範遺囑執行人之補選與指定程序。當遺囑未指定時，優先由親屬會議選定，若無法選定則由利害關係人聲請法院指定。",
    legalBasis: "民法第 1211 條（遺囑執行人之指定與選定）",
    relatedArticles: ["art1210", "art1211", "art1215"],
    essayPrompt: "請論述遺囑執行人的法律地位、職務權限與其對遺產管理之重要性。",
    essayHint: "可從民法第 1215 條（遺囑執行人管理遺產與代理繼承人地位）及第 1211 條切入討論。",
    tags: ["遺囑執行人", "親屬會議", "遺產管理"],
    imageUrl: "images/aljozb5-1c0d199e577f.webp",
  },
  {
    id: "inheritance-020",
    villageId: "inheritance",
    title: "遺囑執行人的職務與法律地位",
    chapter: "第五章 繼承",
    difficulty: "medium" as const,
    story: [
      "林伯伯立下遺囑並指定律師王大為遺囑執行人。",
      "林伯伯過世後，王律師依法接管遺產並進行清點與分配執行。",
      "部分繼承人認為王律師只是局外人，無權干涉或管理遺產，甚至要求王律師立刻交出所有鑰匙與帳冊。",
    ],
    question: "根據民法規定，遺囑執行人執行職務所為之行為，在法律上視為何人的代理？",
    choices: [
      { id: 1, text: "視為被繼承人的代理人", isCorrect: false, explanation: "被繼承人已死亡，代理權消滅，並非被繼承人之代理。" },
      { id: 2, text: "視為繼承人之代理人", isCorrect: true, explanation: "根據民法第 1215 條第 2 項，遺囑執行人因管理遺產及執行上必要行為所為之行為，視為繼承人之代理。" },
      { id: 3, text: "視為法院之法定代理人", isCorrect: false, explanation: "遺囑執行人為私法上執行人，非法院法定代理。" },
      { id: 4, text: "屬於獨立法人，不代表任何人", isCorrect: false, explanation: "法條明確擬制為繼承人之代理。" },
    ],
    explanation: "民法第 1215 條明定，遺囑執行人有管理遺產並為執行上必要行為之職務，其所為之行為視為繼承人之代理，以確保遺囑順利實現。",
    legalBasis: "民法第 1215 條（遺囑執行人之職務與代理效果）",
    relatedArticles: ["art1211", "art1215"],
    essayPrompt: "請說明遺囑執行人的資格限制、職務範圍及其與繼承人間之法律關係。",
    essayHint: "可從民法第 1215 條（代理效果）、第 1198 條（見證人資格限制與執行人關聯）切入分析。",
    tags: ["遺囑執行人", "遺產管理", "代理效力"],
    imageUrl: "images/zpfix7x-e8f6492b8d80.webp",
  },
];
