export const NEW_OBLIGATION_SCENARIOS = [
  {
    id: "obligation-017",
    villageId: "obligation",
    title: "定金的沒收與加倍返還",
    chapter: "第二章 債編",
    difficulty: "medium" as const,
    story: [
      "小強看中一間預售屋，與建商簽訂房屋買賣預約，並支付了 20 萬元定金。",
      "幾天後，小強因為自身財務規劃改變，決定不買這間房子了，並要求建商退還 20 萬元定金。",
      "建商拒絕退還，並主張定金已經被小強違約沒收。",
      "小強則認為建商根本還沒交屋，扣留全額定金很不合理。",
    ],
    question: "根據民法規定，契約因可歸責於付定金當事人的事由致不能履行時，定金的法律效果為何？",
    choices: [
      { id: 1, text: "定金應全數退還給付定金之人", isCorrect: false, explanation: "可歸責於付定金人時，定金不得請求返還。" },
      { id: 2, text: "定金不得請求返還", isCorrect: true, explanation: "根據民法第 249 條第 2 款，契約因可歸責於付定金當事人之事由，致不能履行時，定金不得請求返還。" },
      { id: 3, text: "受定金人須加倍返還定金", isCorrect: false, explanation: "加倍返還適用於可歸責於受定金人的情形。" },
      { id: 4, text: "定金應扣除行政規費後退還一半", isCorrect: false, explanation: "法律無此規定，定金具擔保契約履行之效力。" },
    ],
    explanation: "民法第 249 條第 2 款明定，契約因可歸責於付定金當事人之事由致不能履行時，定金不得請求返還。因此小強無法要求建商退還該筆 20 萬元定金。",
    legalBasis: "民法第 249 條（定金之效力）",
    relatedArticles: ["art249"],
    essayPrompt: "請比較定金、違約金與解約金在契約法上的功能與法律效果。",
    essayHint: "可從民法第 249 條（定金）、第 250 條與第 252 條（違約金與酌減）切入，討論其擔保與賠償總額預定之性質。",
    tags: ["定金", "契約履行", "違約"],
    imageUrl: "images/dbpdpdy-b0c70945a4d1.webp",
  },
  {
    id: "obligation-018",
    villageId: "obligation",
    title: "過高違約金的法院酌減",
    chapter: "第二章 債編",
    difficulty: "hard" as const,
    story: [
      "陳老闆向廠商訂購一批機器設備，雙方約定若遲延交貨，每日須按總價金的百分之五支付違約金。",
      "後來廠商因颱風與供應鏈延誤，遲交了 10 天，累積的違約金竟然高達設備總價的一半。",
      "廠商認為這筆違約金過於懲罰性，請求法院予以酌減，陳老闆則堅持白紙黑字必須照約履行。",
    ],
    question: "關於契約約定的違約金過高時，法院之權限下列何者正確？",
    choices: [
      { id: 1, text: "基於契約自由原則，法院絕對不得干預或酌減", isCorrect: false, explanation: "民法明文賦予法院對過高違約金酌減的權限。" },
      { id: 2, text: "約定之違約金額過高者，法院得減至相當之數額", isCorrect: true, explanation: "根據民法第 252 條，約定之違約金額過高者，法院得減至相當之數額。" },
      { id: 3, text: "違約金只要超過本金一成即屬無效", isCorrect: false, explanation: "法律並未規定超過一成即屬無效，而是由法院依客觀事實衡平酌減。" },
      { id: 4, text: "僅限消費者保護案件始能酌減違約金", isCorrect: false, explanation: "民法第 252 條適用於一般民事契約，不限於消保事件。" },
    ],
    explanation: "民法第 252 條規定，約定之違約金額過高者，法院得減至相當之數額。此為維護契約正義及避免債務人遭受過苛負擔之強制規定。",
    legalBasis: "民法第 252 條（違約金酌減）",
    relatedArticles: ["art252"],
    essayPrompt: "請論述懲罰性違約金與賠償額預定性違約金的區別，以及法院酌減違約金的審酌標準。",
    essayHint: "可從民法第 250 條與實務見解切入，討論債務人是否已一部履行、債權人所受損害狀況及社會經濟狀況。",
    tags: ["違約金", "酌減", "契約正義"],
    imageUrl: "images/bzqnfov-64f54b5b31ba.webp",
  },
  {
    id: "obligation-019",
    villageId: "obligation",
    title: "承攬契約中定作人的協力義務",
    chapter: "第二章 債編",
    difficulty: "medium" as const,
    story: [
      "裝潢師傅阿大承接了林小姐的房屋翻修工程，雙方約定於一個月內完工。",
      "但在工程進行到一半時，林小姐遲遲不肯提供室內設計圖面與挑選好的磁磚建材，導致阿大無法繼續施工。",
      "林小姐卻反控阿大進度嚴重落後，要求阿大賠償延遲完工的違約金。",
    ],
    question: "工作需定作人之行為始能完成，而定作人不為其行為時，承攬人得採取何種法律行動？",
    choices: [
      { id: 1, text: "承攬人僅能默默等待，不得解除契約", isCorrect: false, explanation: "承攬人在定作人不為協力時，可定相當期限催告。" },
      { id: 2, text: "承攬人得定相當期限催告其為之，期滿不為者得解除契約並請求損害賠償", isCorrect: true, explanation: "根據民法第 507 條，工作需定作人之行為始能完成，而定作人不為其行為時，承攬人得定相當期限催告其為之；不於期限內為者，得解除契約並請求損害賠償。" },
      { id: 3, text: "承攬人可直接拍賣林小姐的房屋抵償報酬", isCorrect: false, explanation: "私自拍賣他人財產違法，無此權利。" },
      { id: 4, text: "契約自動失效，雙方互不賠償", isCorrect: false, explanation: "契約不會自動解除，須經法定催告與解除程序。" },
    ],
    explanation: "民法第 507 條保障承攬人的權益。當工作需要定作人（客戶）配合協力卻不配合時，承攬人可經相當期限催告後解除契約並求償。",
    legalBasis: "民法第 507 條（定作人協力義務與承攬人解除權）",
    relatedArticles: ["art507"],
    essayPrompt: "請說明承攬契約中「定作人之協力義務」的性質及其違反的法律效果。",
    essayHint: "可從民法第 507 條出發，討論定作人協力義務屬於不真正義務或從給付義務，以及遲延協力對承攬人完工期限與解除權之影響。",
    tags: ["承攬", "協力義務", "解除契約"],
    imageUrl: "images/mzry3oj-f2d8bd74ae72.webp",
  },
  {
    id: "obligation-020",
    villageId: "obligation",
    title: "保證人的責任與範圍",
    chapter: "第二章 債編",
    difficulty: "medium" as const,
    story: [
      "小明向銀行申辦創業貸款 100 萬元，商請叔叔擔任他的連帶保證人。",
      "後來小明因經營不善倒閉，無力償還貸款，銀行直接向叔叔請求清償全額本息。",
      "叔叔認為：『我是保證人，銀行應該先去跟小明要錢，怎麼可以找我！』",
      "雙方對保證人的責任順序與範圍產生爭議。",
    ],
    question: "根據民法規定，普通保證人與債權人之間享有哪些重要權利？",
    choices: [
      { id: 1, text: "先訴抗辯權，即得主張債權人應先向主債務人強制執行而無效果前拒絕清償", isCorrect: true, explanation: "根據民法第 745 條，保証人於債權人未就主債務人之財產強制執行而無效果前，對於債權人得拒絕清償（先訴抗辯權）。" },
      { id: 2, text: "保證人無條件隨時可免除一切保證責任", isCorrect: false, explanation: "保證人一旦簽約即須負擔相應的擔保責任。" },
      { id: 3, text: "保證人可直接撤銷主債務契約", isCorrect: false, explanation: "撤銷權原則上屬於主債務人，保證人有其代位與抗辯權，但非直接撤銷主契約。" },
      { id: 4, text: "銀行必須獲得法院同意才能向保證人發函催告", isCorrect: false, explanation: "催告無需法院同意，但普通保證人可行使先訴抗辯權。" },
    ],
    explanation: "民法第 739 條定義保證契約，而第 745 條賦予普通保證人「先訴抗辯權」。不過實務上常簽訂「連帶保證人」，連帶保證人拋棄先訴抗辯權，須負與主債務人相同的連帶清償責任。",
    legalBasis: "民法第 739 條、第 745 條（保證與先訴抗辯權）",
    relatedArticles: ["art739"],
    essayPrompt: "請比較普通保證人與連帶保證人在責任承擔與先訴抗辯權上的重大差異。",
    essayHint: "可從民法第 739 條、第 745 條及實務運作切入，討論連帶保證人雖無先訴抗辯權但享有主債務人之抗辯權。",
    tags: ["保證人", "先訴抗辯權", "連帶保證"],
    imageUrl: "images/fejkqvx-78544f62fff4.webp",
  },
];
