export const NEW_PROPERTY_SCENARIOS = [
  {
    id: "property-017",
    villageId: "property",
    title: "袋地通行權的範圍與償金",
    chapter: "第三章 物權",
    difficulty: "medium" as const,
    story: [
      "老王擁有一筆位於山區深處的土地，四周完全被其他人的私人土地包圍，與公路沒有適宜的聯絡。",
      "老王為了出入，必須借道鄰居小李的土地通行。",
      "小李同意老王通行，但要求老王必須支付高額的通行費，並主張走最遠的小徑以保護其隱私。",
      "雙方對通行位置與償金多寡無法達成共識。",
    ],
    question: "根據民法規定，袋地通行權人應如何選擇通行道路與支付償金？",
    choices: [
      { id: 1, text: "可任意穿越他人庭院正中央，且完全不必支付任何補償", isCorrect: false, explanation: "應選擇損害最少之處所，且依法應支付償金。" },
      { id: 2, text: "應於通行必要之範圍內，擇其周圍地損害最少之處所及方法為之，並支付償金", isCorrect: true, explanation: "根據民法第 787 條，土地因與公路無適宜之聯絡致不能為通常使用者，土地所有人得通行周圍地以至公路，並應於必要範圍內擇損害最少之處所及方法為之，且應支付償金。" },
      { id: 3, text: "必須花費巨資開挖隧道，不得穿越他人地面", isCorrect: false, explanation: "法律允許通行周圍地，不強求不合理的巨資隧道。" },
      { id: 4, text: "通行地所有人可隨時無條件封閉道路", isCorrect: false, explanation: "袋地通行權係法定物權，不得任意封閉。" },
    ],
    explanation: "民法第 787 條規定袋地通行權，旨在發揮土地經濟效用。通行時應採損害最少之處所及方法，並對通行地因此所受之損害支付償金。",
    legalBasis: "民法第 787 條（袋地通行權與償金）",
    relatedArticles: ["art767", "art787"],
    essayPrompt: "請說明袋地通行權的法律性質與相鄰關係限制之立法目的。",
    essayHint: "可從民法第 774 條相鄰關係與第 787 條袋地通行權切入，討論所有權社會化與物權調和鄰地利益之意涵。",
    tags: ["袋地通行權", "相鄰關係", "物權"],
    imageUrl: "images/ly3znp-117ee2743cc7.webp",
  },
  {
    id: "property-018",
    villageId: "property",
    title: "區分所有建築物的共有與專有",
    chapter: "第三章 物權",
    difficulty: "hard" as const,
    story: [
      "阿明購買了一棟大樓的頂樓專有住宅，並順便取得了大樓屋頂平臺的使用權。",
      "幾個月後，阿明想要把屋頂平臺登記並獨立分割出售給社區以外的第三人。",
      "社區管委會及其他住戶紛紛出面反對，認為屋頂平臺屬於全體共有的共有部分，不得與專有部分分離轉讓。",
    ],
    question: "根據民法規定，專有部分與其所屬之共有部分及基地之權利，其移轉關係為何？",
    choices: [
      { id: 1, text: "專有部分與共有部分可隨時自由分別獨立轉讓", isCorrect: false, explanation: "法律禁止專有部分與共有部分分離而為移轉或設定負擔。" },
      { id: 2, text: "專有部分與其所屬之共有部分及其基地之權利，不得分離而為移轉或設定負擔", isCorrect: true, explanation: "根據民法第 799 條第 5 項，專有部分與其所屬之共有部分及其基地之權利，不得分離而為移轉或設定負擔。" },
      { id: 3, text: "僅頂樓住戶可單獨買賣屋頂平臺", isCorrect: false, explanation: "屋頂平臺屬共同部分或依約定專用，不得與主建物分離獨立移轉給社區外第三人。" },
      { id: 4, text: "建商保留所有權，住戶無權干涉", isCorrect: false, explanation: "區分所有建築物之共有部分屬全體區分所有人共有，建商不得保留分離處分權。" },
    ],
    explanation: "民法第 799 條第 5 項明定，專有部分與其所屬之共有部分及其基地之權利，不得分離而為移轉或設定負擔，以維護大樓社區之整體安定與法律秩序。",
    legalBasis: "民法第 799 條（區分所有建築物）",
    relatedArticles: ["art758", "art799"],
    essayPrompt: "請論述區分所有建物中專有部分、共有部分及基地應有部分不可分離性之法理基礎。",
    essayHint: "可從民法第 799 條與公寓大廈管理條例切入，討論建物與基地一體性及維護居住安全之考量。",
    tags: ["區分所有", "共有部分", "不得分離"],
    imageUrl: "images/e2tisaz-efeb99cff3c7.webp",
  },
  {
    id: "property-019",
    villageId: "property",
    title: "共有物管理的過半數決",
    chapter: "第三章 物權",
    difficulty: "medium" as const,
    story: [
      "一筆土地由 A、B、C 三人分別共有，A 持有 50%，B 持有 30%，C 持有 20%。",
      "A 與 B 共同決定將該筆土地出租給某大型超商營運，租期五年。",
      "C 強烈反對，認為出租決定未經全體共有人一致同意，因此該租賃契約無效。",
    ],
    question: "根據民法規定，共有物之管理（如出租）除契約另有約定外，應如何決定？",
    choices: [
      { id: 1, text: "必須經全體共有人 100% 一致同意始得為之", isCorrect: false, explanation: "管理行為不以全體一致為必要，多數決即可。" },
      { id: 2, text: "應以共有人過半數及其應有部分合計過半數之同意行之（或應有部分合計逾三分之二）", isCorrect: true, explanation: "根據民法第 820 條第 1 項，共有物之管理，除契約另有約定外，應以共有人過半數及其應有部分合計過半數之同意行之。但其應有部分合計逾三分之二者，其人數不予計算。" },
      { id: 3, text: "持分最大的人可單獨決定一切事務，不需其他人同意", isCorrect: false, explanation: "單獨決定重大管理仍須符合法定應有部分比例門檻。" },
      { id: 4, text: "共有土地一律不得出租，只能空置", isCorrect: false, explanation: "符合法定多數決即可合法出租管理。" },
    ],
    explanation: "民法第 820 條規定共有物之管理採多數決。在本案中 A 與 B 合計持有 80%（逾三分之二），故其出租管理決定合法有效，C 雖反對仍受拘束。",
    legalBasis: "民法第 820 條（共有物之管理）",
    relatedArticles: ["art765", "art820"],
    essayPrompt: "請比較共有物的「保存行為」、「管理行為」與「處分變更」在民法上的決議門檻差異。",
    essayHint: "可從民法第 820 條（管理與保存，保存可單獨為之）、第 819 條（處分、變更與設定負擔須全體同意）切入分析。",
    tags: ["共有物管理", "多數決", "分別共有"],
    imageUrl: "images/urnbj5-51487711d7b1.webp",
  },
  {
    id: "property-020",
    villageId: "property",
    title: "占有輔助人與直接占有",
    chapter: "第三章 物權",
    difficulty: "medium" as const,
    story: [
      "老闆阿強將店裡的一台專業咖啡機交給店員小美使用並負責煮咖啡販售。",
      "某日小偷闖入店內企圖搶走咖啡機，小美見狀立刻出面阻止並保全咖啡機。",
      "事後有人爭議說小美只是受僱店員，並非咖啡機的法律占有人，無權行使占有物防禦權。",
    ],
    question: "店員受老闆指示對於店內物品有管領之力者，在民法上稱為何種關係？",
    choices: [
      { id: 1, text: "直接占有人", isCorrect: false, explanation: "直接占有人是老闆阿強，店員屬於占有輔助人。" },
      { id: 2, text: "占有輔助人", isCorrect: true, explanation: "根據民法第 942 條，受僱人、學徒、家屬或基於其他類似之關係，受他人之指示，而對於物有管領之力者，僅該他人為占有人（店員為占有輔助人）。" },
      { id: 3, text: "間接占有人", isCorrect: false, explanation: "間接占有人如出租人或出質人，與店員性質不同。" },
      { id: 4, text: "無權占有人", isCorrect: false, explanation: "受僱人基於合法雇用指示管領物，並非無權占有。" },
    ],
    explanation: "民法第 942 條規定「占有輔助人」。受僱人雖實際管領物品，但法律上的占有人仍是老闆。不過占有輔助人基於社會常態與防衛需要，仍可依據實務見解協助行使自力救濟或占有防禦。",
    legalBasis: "民法第 942 條（占有輔助人）",
    relatedArticles: ["art942", "art966"],
    essayPrompt: "請說明直接占有、間接占有與占有輔助人的區別及法律保護範圍。",
    essayHint: "可從民法第 941 條（間接占有）、第 942 條（占有輔助人）與第 943 條（占有之推定）出發，討論物權法上占有保護制度的實益。",
    tags: ["占有輔助人", "受僱人", "占有保護"],
    imageUrl: "images/hzzjoc-d43a1ef2c15d.webp",
  },
];
