const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const OBLIGATION_BATCH_4_ARTICLES=[
 {id:"ob4-294",number:"第294條",title:"債權讓與",content:"債權人得將債權讓與第三人；依性質、特約或禁止扣押不得讓與者例外。",chapter:"債權讓與",villageId:"obligation"},
 {id:"ob4-297",number:"第297條",title:"債權讓與的通知",content:"債權讓與未經讓與人或受讓人通知債務人，對債務人不生效；提示讓與字據與通知同效。",chapter:"債權讓與",villageId:"obligation"},
 {id:"ob4-301",number:"第301條",title:"債務承擔的債權人承認",content:"第三人與債務人訂立契約承擔債務者，未經債權人承認，對債權人不生效。",chapter:"債務承擔",villageId:"obligation"},
 {id:"ob4-304",number:"第304條",title:"債務承擔與第三人擔保",content:"第三人就債權所為擔保，除該第三人承認債務承擔外，因債務承擔而消滅。",chapter:"債務承擔",villageId:"obligation"},
 {id:"ob4-305",number:"第305條",title:"概括承受資產負債",content:"概括承受他人資產及負債者，對債權人通知或公告生承擔效力；原債務人對法定期間內債權與承擔人連帶負責。",chapter:"債務承擔",villageId:"obligation"},
];
export const OBLIGATION_BATCH_4_SCENARIOS=[
 {id:"obligation-036",villageId:"obligation",title:"讓與出去的攝影款",chapter:"債權讓與",difficulty:"medium",story:["攝影師小芸對公司有一筆已到期的商業攝影款。","她想把這筆金錢債權讓與朋友以換取現金。"],question:"依民法第294條，何者正確？",choices:[c(1,"金錢債權原則上可讓與第三人。",true,"正確。債權讓與原則自由，僅有性質、特約或禁止扣押等例外。"),c(2,"所有債權都絕對不得讓與。",false,"錯誤。條文原則是得讓與。"),c(3,"讓與後債權必然消滅。",false,"錯誤。是債權主體變更，不是債權消滅。"),c(4,"不得讓與特約可對抗所有善意第三人。",false,"錯誤。第294條對善意第三人有特別規定。")],relatedArticles:["ob4-294"],essayPrompt:"說明債權讓與原則與三類例外。",essayHint:"列出性質、特約與禁止扣押例外。",tags:["債權讓與","攝影款"],imageUrl,legalBasis:"民法第294條"},
 {id:"obligation-037",villageId:"obligation",title:"未通知的帳款讓與",chapter:"債權讓與",difficulty:"medium",story:["房東將租金債權讓與給表哥，卻沒有通知租客阿強。","阿強照舊向房東付款後，表哥才要求阿強再付款。"],question:"依民法第297條，何者正確？",choices:[c(1,"未經通知前，讓與對阿強不生效。",true,"正確。讓與人或受讓人通知債務人前，債權讓與不對債務人生效。"),c(2,"表哥可直接要求阿強重複付款。",false,"錯誤。題目未通知，讓與對債務人不生效。"),c(3,"債權讓與必須經法院判決。",false,"錯誤。條文重點是通知或提示讓與字據。"),c(4,"只有房東親自通知才有效。",false,"錯誤。受讓人通知或提示讓與字據亦可。")],relatedArticles:["ob4-297"],essayPrompt:"說明債權讓與通知對債務人的意義。",essayHint:"區分讓與契約與其對債務人的效力。",tags:["債權讓與","通知","租金"],imageUrl,legalBasis:"民法第297條"},
 {id:"obligation-038",villageId:"obligation",title:"新屋主承擔的社區費",chapter:"債務承擔",difficulty:"medium",story:["前屋主與新屋主約定由新屋主承擔積欠的社區管理費。","管委會並未承認這項安排。"],question:"依民法第301條，何者正確？",choices:[c(1,"未經管委會承認，該承擔對管委會不生效。",true,"正確。第三人與債務人間的債務承擔，須經債權人承認才對債權人生效。"),c(2,"私下約定必然使前屋主立即對管委會免責。",false,"錯誤。未經債權人承認，不能對抗債權人。"),c(3,"新屋主只要口頭承諾，管委會一定受拘束。",false,"錯誤。仍須債權人承認。"),c(4,"債權人永遠不能承認債務承擔。",false,"錯誤。第301條正以債權人承認為生效要件。")],relatedArticles:["ob4-301"],essayPrompt:"說明債務人與第三人約定承擔債務時，債權人承認的重要性。",essayHint:"指出未承認時只是不對債權人生效。",tags:["債務承擔","社區費"],imageUrl,legalBasis:"民法第301條"},
 {id:"obligation-039",villageId:"obligation",title:"換債務人後的保證",chapter:"債務承擔",difficulty:"hard",story:["阿哲替朋友的車貸提供保證，後來另一人承擔該車貸。","阿哲沒有承認這次債務承擔。"],question:"依民法第304條，何者正確？",choices:[c(1,"阿哲提供的第三人保證原則上因債務承擔而消滅。",true,"正確。除非提供擔保的第三人承認債務承擔，否則其擔保因承擔而消滅。"),c(2,"保證必然永久不受債務承擔影響。",false,"錯誤。第304條有特別規定。"),c(3,"阿哲是否承認完全沒有意義。",false,"錯誤。其承認是擔保存續的重要例外。"),c(4,"債務承擔不會涉及任何從屬權利。",false,"錯誤。第304條即規範從屬權利與擔保。")],relatedArticles:["ob4-304"],essayPrompt:"說明債務承擔後第三人擔保的原則及例外。",essayHint:"抓住提供擔保的第三人是否承認。",tags:["債務承擔","保證","車貸"],imageUrl,legalBasis:"民法第304條"},
 {id:"obligation-040",villageId:"obligation",title:"整店轉讓後的供應商帳款",chapter:"債務承擔",difficulty:"hard",story:["老闆將咖啡店營業、設備與債務整體轉讓給新業者，並公告給供應商。","供應商想知道原老闆是否立刻完全免責。"],question:"依民法第305條，何者正確？",choices:[c(1,"通知或公告後生債務承擔效力，原老闆在法定兩年期間仍與新業者連帶負責。",true,"正確。概括承受公告或通知後生效，原債務人在第305條期間仍有連帶責任。"),c(2,"公告後原老闆立刻永遠免責。",false,"錯誤。條文规定特定期間連帶責任。"),c(3,"概括承受永遠不會產生債務承擔效力。",false,"錯誤。通知或公告即為法定要件。"),c(4,"只有新業者可以對供應商負責。",false,"錯誤。原債務人在法定期間仍連帶負責。")],relatedArticles:["ob4-305"],essayPrompt:"說明概括承受資產負債後，通知或公告及原債務人兩年連帶責任的意義。",essayHint:"區分到期與未到期債權的期間起算。",tags:["概括承受","營業讓與","供應商"],imageUrl,legalBasis:"民法第305條"}
];
