const imageUrl = "https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/obligation-016-C2jdVdwzMe8GTXf5KRNJqk.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const OBLIGATION_BATCH_3_ARTICLES=[
 {id:"ob3-271",number:"第271條",title:"可分債務的平均分擔",content:"數人負同一債務而給付可分者，除法律或契約另定外，應各平均分擔。",chapter:"多數債務人",villageId:"obligation"},
 {id:"ob3-273",number:"第273條",title:"連帶債務人的對外責任",content:"連帶債務之債權人得對債務人中一人、數人或全體，同時或先後請求全部或一部給付。",chapter:"多數債務人",villageId:"obligation"},
 {id:"ob3-278",number:"第278條",title:"債權人遲延的效力",content:"債權人對連帶債務人中之一人有遲延時，為他債務人之利益，亦生效力。",chapter:"多數債務人",villageId:"obligation"},
 {id:"ob3-281",number:"第281條",title:"連帶債務人間的求償",content:"連帶債務人中之一人清償致他債務人同免責時，得向他債務人請求償還各自分擔部分及利息。",chapter:"多數債務人",villageId:"obligation"},
 {id:"ob3-287",number:"第287條",title:"連帶債權人的判決效力",content:"連帶債權人中之一人受有利益的確定判決，為其他債權人利益亦生效力。",chapter:"多數債權人",villageId:"obligation"},
];
export const OBLIGATION_BATCH_3_SCENARIOS=[
 {id:"obligation-031",villageId:"obligation",title:"未約定連帶的清潔費",chapter:"多數債務人",difficulty:"medium",story:["三名室友共同訂購可分的社區清潔服務，契約沒有約定連帶責任。","業者要求其中一人一次負擔全部九千元。"],question:"依民法第271條，何者正確？",choices:[c(1,"三人原則上各平均分擔三千元。",true,"正確。可分的同一債務，除法律或契約另定外，數人平均分擔。"),c(2,"只要有三人，業者當然可向一人請求全部。",false,"錯誤。這是連帶責任的效果，題目未約定連帶。"),c(3,"三人完全不必負責。",false,"錯誤。各人仍應分擔債務。"),c(4,"金額可分時必須由業者自行承擔。",false,"錯誤。第271條規定平均分擔。")],relatedArticles:["ob3-271"],essayPrompt:"比較可分債務與連帶債務。",essayHint:"先判斷是否有法律或契約的連帶約定。",tags:["可分債務","分擔"],imageUrl,legalBasis:"民法第271條"},
 {id:"obligation-032",villageId:"obligation",title:"共同借款的連帶責任",chapter:"多數債務人",difficulty:"medium",story:["阿豪與阿哲借款時明定負連帶責任。","銀行向阿豪請求尚未清償的全部借款。"],question:"依民法第273條，何者正確？",choices:[c(1,"銀行得向阿豪請求全部或一部給付。",true,"正確。連帶債務債權人得向一人、數人或全體請求。"),c(2,"銀行只能各請求一半。",false,"錯誤。那是可分債務而非連帶債務。"),c(3,"銀行必須同時起訴二人。",false,"錯誤。可先後或同時請求。"),c(4,"阿豪只要說阿哲也存在便免責。",false,"錯誤。未全部履行前仍負連帶責任。")],relatedArticles:["ob3-273"],essayPrompt:"說明連帶債務的對外效力。",essayHint:"區分債權人對外請求和債務人內部分擔。",tags:["連帶債務","借款"],imageUrl,legalBasis:"民法第273條"},
 {id:"obligation-033",villageId:"obligation",title:"被拒收的完整清償",chapter:"多數債務人",difficulty:"hard",story:["兩名連帶債務人中，阿明備妥全額向債權人清償。","債權人無正當理由拒絕受領。"],question:"依民法第278條，何者正確？",choices:[c(1,"債權人對阿明的受領遲延，為另一債務人的利益亦生效。",true,"正確。第278條明定此一效力。"),c(2,"只影響阿明，另一人完全不受影響。",false,"錯誤。法律為其他債務人利益亦使其生效。"),c(3,"拒收會使債務當然消滅。",false,"錯誤。題目是受領遲延效力。"),c(4,"連帶債務人不得清償全額。",false,"錯誤。連帶債務人可為全額清償。")],relatedArticles:["ob3-278"],essayPrompt:"說明受領遲延在連帶債務中的效力。",essayHint:"抓住債權人對其中一人的遲延及對他人的利益。",tags:["連帶債務","受領遲延"],imageUrl,legalBasis:"民法第278條"},
 {id:"obligation-034",villageId:"obligation",title:"替室友清償的欠租",chapter:"多數債務人",difficulty:"hard",story:["三名共同承租人對房東負連帶欠租。","阿美為避免訴訟清償全部九萬元，使其他人也免責。"],question:"阿美依民法第281條可如何主張？",choices:[c(1,"向其他人請求各自應分擔的部分及自免責時起利息。",true,"正確。清償使他人同免責者，有內部求償權。"),c(2,"只能自行吸收全部租金。",false,"錯誤。第281條賦予求償。"),c(3,"可任意要求其中一人償還全部九萬，無須看分擔。",false,"錯誤。求償以各自分擔部分為限。"),c(4,"清償後仍可向房東再請求租金。",false,"錯誤。清償的是對外債務。")],relatedArticles:["ob3-281"],essayPrompt:"說明連帶債務人清償後的內部求償。",essayHint:"區分對外連帶責任與內部各自分擔部分。",tags:["連帶債務","求償","租金"],imageUrl,legalBasis:"民法第281條"},
 {id:"obligation-035",villageId:"obligation",title:"共同受款人的有利判決",chapter:"多數債權人",difficulty:"hard",story:["甲、乙為連帶債權人，甲先就共同債權取得有利確定判決。","乙主張此判決也有助於自己的權利。"],question:"依民法第287條，何者正確？",choices:[c(1,"甲受有利益的確定判決，為乙利益亦生效。",true,"正確。第287條第一項明定有利判決的擴張效力。"),c(2,"判決永遠只影響甲。",false,"錯誤。對其他連帶債權人亦生效。"),c(3,"乙須重新取得完全相同判決才有任何利益。",false,"錯誤。法律已有有利判決效力規定。"),c(4,"連帶債權人不存在判決效力問題。",false,"錯誤。第287條專門規定。")],relatedArticles:["ob3-287"],essayPrompt:"說明連帶債權人中有利確定判決的效力。",essayHint:"點出有利判決為其他債權人利益亦生效。",tags:["連帶債權","確定判決"],imageUrl,legalBasis:"民法第287條"}
];
