const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const PROPERTY_BATCH_1_ARTICLES=[
 {id:"pb1-765",number:"第765條",title:"所有權權能",content:"所有人於法令限制內，得自由使用、收益、處分所有物，並排除他人干涉。",chapter:"所有權",villageId:"property"},
 {id:"pb1-767",number:"第767條",title:"物上請求權",content:"所有人得請求無權占有人返還所有物、除去妨害，並防止妨害之虞。",chapter:"所有權",villageId:"property"},
 {id:"pb1-768",number:"第768條",title:"動產取得時效",content:"以所有意思十年間和平、公然、繼續占有他人動產者，取得其所有權。",chapter:"所有權",villageId:"property"},
 {id:"pb1-769",number:"第769條",title:"未登記不動產取得時效",content:"以所有意思二十年間和平、公然、繼續占有他人未登記不動產者，得請求登記為所有人。",chapter:"所有權",villageId:"property"},
 {id:"pb1-770",number:"第770條",title:"善意未登記不動產取得時效",content:"以所有意思十年間和平、公然、繼續占有他人未登記不動產，且占有開始善意無過失者，得請求登記。",chapter:"所有權",villageId:"property"},
];
export const PROPERTY_BATCH_1_SCENARIOS=[
 {id:"property-021",villageId:"property",title:"被占用的自有車位",chapter:"所有權",difficulty:"easy",story:["小文擁有社區車位，陌生人卻經常無權停放並阻礙使用。"],question:"依民法第765條，何者正確？",choices:[c(1,"小文得在法令限制內使用車位並排除他人干涉。",true,"正確。所有權包括使用、收益、處分及排除干涉。"),c(2,"所有人不得使用自己的車位。",false,"錯誤。使用是所有權基本權能。"),c(3,"任何人均可無權使用。",false,"錯誤。所有人得排除干涉。"),c(4,"所有權完全不受法令限制。",false,"錯誤。條文明定於法令限制範圍內。")],relatedArticles:["pb1-765"],essayPrompt:"說明所有權的四項基本權能。",essayHint:"使用、收益、處分與排除干涉。",tags:["所有權","車位"],imageUrl,legalBasis:"民法第765條"},
 {id:"property-022",villageId:"property",title:"私有走道的堆置物",chapter:"所有權",difficulty:"medium",story:["鄰居把雜物堆在小林私有走道，並說下週還會再放更多。"],question:"依民法第767條，小林可主張何者？",choices:[c(1,"請求除去現有妨害，並防止將來妨害。",true,"正確。對妨害得請求除去，對妨害之虞得請求防止。"),c(2,"只能忍受，不能主張。",false,"錯誤。所有人有物上請求權。"),c(3,"只能請求損害賠償，不能除去。",false,"錯誤。第767條直接規定除去妨害。"),c(4,"只能等對方取得所有權。",false,"錯誤。無權妨害不生所有權。")],relatedArticles:["pb1-767"],essayPrompt:"區分返還、除去與防止請求權。",essayHint:"依無權占有、既有妨害與妨害之虞分類。",tags:["物上請求權","走道"],imageUrl,legalBasis:"民法第767條"},
 {id:"property-023",villageId:"property",title:"十年管理的老腳踏車",chapter:"所有權",difficulty:"hard",story:["阿德以所有人身分和平、公然、持續管理一輛他人腳踏車已滿十年。"],question:"依民法第768條，何者正確？",choices:[c(1,"符合要件時，取得該動產所有權。",true,"正確。動產以所有意思十年和平、公然、繼續占有可取得所有權。"),c(2,"動產必須占有二十年。",false,"錯誤。第768條為十年。"),c(3,"只要保管一天就可取得。",false,"錯誤。需滿十年及其他要件。"),c(4,"必須是登記不動產。",false,"錯誤。本條對象為動產。")],relatedArticles:["pb1-768"],essayPrompt:"列出動產取得時效要件。",essayHint:"所有意思、十年、和平、公然、繼續與動產。",tags:["取得時效","動產"],imageUrl,legalBasis:"民法第768條"},
 {id:"property-024",villageId:"property",title:"二十年的未登記農地",chapter:"所有權",difficulty:"hard",story:["阿良以所有人意思和平、公然、繼續使用他人未登記農地二十年。"],question:"依民法第769條，何者正確？",choices:[c(1,"阿良得請求登記為所有人。",true,"正確。未登記不動產滿二十年取得時效，可請求登記。"),c(2,"十年即必然取得。",false,"錯誤。普通要件為二十年。"),c(3,"任何登記土地也可適用。",false,"錯誤。本條限未登記不動產。"),c(4,"占有不須以所有意思。",false,"錯誤。條文明定以所有之意思。")],relatedArticles:["pb1-769"],essayPrompt:"說明第769條的年限與標的限制。",essayHint:"二十年、未登記不動產及所有意思。",tags:["取得時效","農地"],imageUrl,legalBasis:"民法第769條"},
 {id:"property-025",villageId:"property",title:"善意買受的未登記土地",chapter:"所有權",difficulty:"hard",story:["阿芳善意且無過失地相信自己買到一塊未登記土地，並以所有人意思和平、公然占有十年。"],question:"依民法第770條，何者正確？",choices:[c(1,"符合要件時，阿芳得請求登記為所有人。",true,"正確。第770條在占有開始善意無過失時縮短為十年。"),c(2,"善意無過失完全不重要。",false,"錯誤。此為第770條加重要件。"),c(3,"只要五年即可。",false,"錯誤。條文规定十年。"),c(4,"標的必須是動產。",false,"錯誤。此處為未登記不動產。")],relatedArticles:["pb1-770"],essayPrompt:"比較第769與第770條。",essayHint:"比較二十年與十年，以及善意無過失要件。",tags:["取得時效","善意","不動產"],imageUrl,legalBasis:"民法第770條"}
];
