const imageUrl="https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/obligation-016-C2jdVdwzMe8GTXf5KRNJqk.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const PROPERTY_BATCH_2_ARTICLES=[
 {id:"pb2-771",number:"第771條",title:"取得時效的中斷",content:"所有人依第767條起訴請求占有人返還占有物者，占有人所有權取得時效中斷。",chapter:"所有權",villageId:"property"},
 {id:"pb2-773",number:"第773條",title:"土地所有權的上下範圍",content:"土地所有權於行使有利益範圍內及於土地上下；無礙行使的他人干涉不得排除。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb2-774",number:"第774條",title:"防免鄰地損害",content:"土地所有人經營事業或行使所有權，應注意防免鄰地損害。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb2-775",number:"第775條",title:"自然流水",content:"土地所有人不得妨阻由鄰地自然流至之水；為鄰地所必需者，不得完全妨阻。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb2-776",number:"第776條",title:"蓄排水工作物",content:"排水工作物阻塞致鄰地損害或有損害之虞時，土地所有人應自費為必要修繕、疏通或預防。",chapter:"相鄰關係",villageId:"property"},
];
export const PROPERTY_BATCH_2_SCENARIOS=[
 {id:"property-026",villageId:"property",title:"返還之訴打斷時效",chapter:"所有權",difficulty:"hard",story:["阿成主張以所有人意思占有未登記土地多年。","真正所有人依第767條起訴請求返還土地。"],question:"依民法第771條，何者正確？",choices:[c(1,"占有人的所有權取得時效因返還之訴而中斷。",true,"正確。第771條明定依第767條起訴返還時效中斷。"),c(2,"起訴完全不影響取得時效。",false,"錯誤。這正是法定中斷事由。"),c(3,"起訴後占有人立即取得所有權。",false,"錯誤。效果是中斷而非取得。"),c(4,"只有口頭抗議會中斷。",false,"錯誤。條文規定起訴返還。")],relatedArticles:["pb2-771"],essayPrompt:"說明取得時效中斷的其中一項法定事由。",essayHint:"指出所有人依第767條起訴返還。",tags:["取得時效","返還之訴"],imageUrl,legalBasis:"民法第771條"},
 {id:"property-027",villageId:"property",title:"不妨礙利用的高空設備",chapter:"相鄰關係",difficulty:"hard",story:["鄰地在高空設置設備，但沒有妨礙阿晴土地的使用或利益。"],question:"依民法第773條，何者正確？",choices:[c(1,"無礙所有權行使的干涉，阿晴不得排除。",true,"正確。土地上下權能以行使有利益範圍為限。"),c(2,"土地所有權當然及於無限高空。",false,"錯誤。限於有利益範圍。"),c(3,"任何高空設備必須拆除。",false,"錯誤。須有妨礙所有權行使。"),c(4,"第773條只規定水流。",false,"錯誤。規定土地上下範圍。")],relatedArticles:["pb2-773"],essayPrompt:"說明土地所有權向上與向下的限制。",essayHint:"關鍵是行使所有權有無利益。",tags:["土地所有權","高空"],imageUrl,legalBasis:"民法第773條"},
 {id:"property-028",villageId:"property",title:"施工震裂的鄰屋牆面",chapter:"相鄰關係",difficulty:"medium",story:["小偉整修店面時長期使用重型機具，震動造成隔壁牆面龜裂。"],question:"依民法第774條，何者正確？",choices:[c(1,"小偉行使所有權仍應注意防免鄰地損害。",true,"正確。第774條明定防免鄰地損害義務。"),c(2,"只要在自己土地施工就不必顧及鄰地。",false,"錯誤。所有權行使受相鄰關係限制。"),c(3,"鄰地受損必然合法。",false,"錯誤。應注意防免損害。"),c(4,"第774條僅適用租賃。",false,"錯誤。適用土地所有人經營或行使所有權。")],relatedArticles:["pb2-774"],essayPrompt:"說明行使所有權時為何仍須防免鄰地損害。",essayHint:"連結相鄰關係與所有權限制。",tags:["相鄰關係","施工"],imageUrl,legalBasis:"民法第774條"},
 {id:"property-029",villageId:"property",title:"被圍牆阻斷的自然排水",chapter:"相鄰關係",difficulty:"medium",story:["高地雨水自然流向低地鄰居，小華築牆完全阻絕水流，造成低地積水。"],question:"依民法第775條，何者正確？",choices:[c(1,"小華不得妨阻自然流入且為鄰地所必需的水。",true,"正確。第775條規範自然流水。"),c(2,"土地所有人可任意完全阻絕自然水流。",false,"錯誤。條文明定不得妨阻。"),c(3,"自然水流與相鄰關係無關。",false,"錯誤。第775條就是相鄰關係規定。"),c(4,"低地必須自行承擔所有阻絕結果。",false,"錯誤。仍受第775條保護。")],relatedArticles:["pb2-775"],essayPrompt:"說明自然流水規則與其限制。",essayHint:"自然流入、鄰地所必需與不得完全妨阻。",tags:["自然流水","圍牆"],imageUrl,legalBasis:"民法第775條"},
 {id:"property-030",villageId:"property",title:"堵塞排水溝的倒灌",chapter:"相鄰關係",difficulty:"medium",story:["阿隆自設排水溝長期堵塞，雨天倒灌到隔壁花圃，且仍有再次損害風險。"],question:"依民法第776條，何者正確？",choices:[c(1,"阿隆原則上應自費修繕、疏通或預防。",true,"正確。排水工作物造成或有造成鄰地損害之虞，應採必要措施。"),c(2,"只要是自己的排水溝就不必維護。",false,"錯誤。條文規定維護義務。"),c(3,"只有已完全毀損才能處理。",false,"錯誤。有損害之虞亦應預防。"),c(4,"費用必然由鄰居負擔。",false,"錯誤。原則為所有人自費，另有習慣者例外。")],relatedArticles:["pb2-776"],essayPrompt:"比較自然流水與人工排水工作物的規則。",essayHint:"第775條與第776條的事實前提不同。",tags:["排水","相鄰關係"],imageUrl,legalBasis:"民法第776條"}
];
