const imageUrl="images/obligation-016-c2jdvdwzme8gtxf5krnjqk-b5e210281d50.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const PROPERTY_BATCH_4_ARTICLES=[
 {id:"pb4-785",number:"第785條",title:"設堰附著對岸",content:"水流地所有人設堰有必要時得附著對岸，但應就所生損害支付償金。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb4-786",number:"第786條",title:"設置管線通過鄰地",content:"設置管線非通過他人土地不能或費用過鉅時，得採損害最少方法通過並支付償金。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb4-787",number:"第787條",title:"袋地通行權",content:"土地無適宜公路聯絡而不能通常使用，且非所有人任意行為所生者，得通行周圍地，並採最小損害方法及付償金。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb4-788",number:"第788條",title:"開設道路與購買請求",content:"有通行權人必要時得開設道路並付償金；通行地受損過鉅時，其所有人得請求以相當價額購買。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb4-789",number:"第789條",title:"分割或讓與形成袋地",content:"因讓與或分割形成袋地者，僅得通行讓與人、受讓人或他分割人土地，且無須支付償金。",chapter:"相鄰關係",villageId:"property"},
];
export const PROPERTY_BATCH_4_SCENARIOS=[
 {id:"property-036",villageId:"property",title:"灌溉堰附著對岸",chapter:"相鄰關係",difficulty:"hard",story:["阿松的水流地設灌溉堰確有必要，堰的一端須固定在對岸鄰地。"],question:"依民法第785條，何者正確？",choices:[c(1,"阿松得附著對岸，但應支付因此所生損害的償金。",true,"正確。有必要得附著，但附有補償義務。"),c(2,"阿松可無條件使用對岸而不補償。",false,"錯誤。條文明定損害應支付償金。"),c(3,"設堰一律不得附著對岸。",false,"錯誤。有必要時得附著。"),c(4,"對岸所有人永遠不得使用堰。",false,"錯誤。符合條件時得依受益程度使用並分擔費用。")],relatedArticles:["pb4-785"],essayPrompt:"說明設堰附著對岸的權利與補償義務。",essayHint:"必要性、對岸損害與償金。",tags:["設堰","償金"],imageUrl,legalBasis:"民法第785條"},
 {id:"property-037",villageId:"property",title:"必經鄰地的自來水管",chapter:"相鄰關係",difficulty:"hard",story:["小玲家沒有其他合理路線可接自來水，若不穿越鄰地便無法設水管。"],question:"依民法第786條，何者正確？",choices:[c(1,"可在損害最少的處所設管並支付償金。",true,"正確。條文要求最小損害與補償。"),c(2,"可任選最方便但最破壞鄰地的路線。",false,"錯誤。必須採損害最少方法。"),c(3,"設管永遠不得通過他人土地。",false,"錯誤。具法定要件時得通過。"),c(4,"使用鄰地管線一定無須補償。",false,"錯誤。原則應支付償金。")],relatedArticles:["pb4-786"],essayPrompt:"列出設置管線通過鄰地的主要要件。",essayHint:"不能或費用過鉅、最小損害與償金。",tags:["水管","管線"],imageUrl,legalBasis:"民法第786條"},
 {id:"property-038",villageId:"property",title:"沒有出路的果園",chapter:"相鄰關係",difficulty:"hard",story:["阿仁的果園沒有適宜道路通往公路，且不是他任意造成的，因此無法通常使用。"],question:"依民法第787條，何者正確？",choices:[c(1,"阿仁得在必要範圍通行周圍地，採最小損害方法並支付償金。",true,"正確。這是一般袋地通行權的法定內容。"),c(2,"阿仁可免費任意穿越所有鄰地。",false,"錯誤。須必要範圍、最小損害與償金。"),c(3,"只要沒有出路即不問原因必然可通行。",false,"錯誤。任意行為造成者不適用。"),c(4,"袋地只能永久閒置。",false,"錯誤。條文提供通行救濟。")],relatedArticles:["pb4-787"],essayPrompt:"說明一般袋地通行權的要件與限制。",essayHint:"公路聯絡、通常使用、非任意行為、最小損害、償金。",tags:["袋地","通行權"],imageUrl,legalBasis:"民法第787條"},
 {id:"property-039",villageId:"property",title:"開路造成過鉅損害",chapter:"相鄰關係",difficulty:"hard",story:["有通行權的阿仁開設道路，使通行地被切成難以利用的小塊，損害過鉅。"],question:"依民法第788條，通行地所有人可主張何者？",choices:[c(1,"請求阿仁以相當價額購買通行地及形成的畸零地。",true,"正確。損害過鉅時有購買請求權。"),c(2,"只能無條件忍受開路。",false,"錯誤。第788條提供特別救濟。"),c(3,"阿仁無須支付任何補償。",false,"錯誤。開路亦應支付償金。"),c(4,"通行地必須無償讓與。",false,"錯誤。是以相當價額購買。")],relatedArticles:["pb4-788"],essayPrompt:"說明必要開路造成過鉅損害時的特別效果。",essayHint:"通行地與畸零地、相當價額與法院判決。",tags:["袋地","開路"],imageUrl,legalBasis:"民法第788條"},
 {id:"property-040",villageId:"property",title:"分割後形成的袋地",chapter:"相鄰關係",difficulty:"hard",story:["同一地主分割出售土地後，內側土地失去公路聯絡，買受人需通行原分割關係人的土地。"],question:"依民法第789條，何者正確？",choices:[c(1,"僅得通行讓與人、受讓人或他分割人土地，且無須付償金。",true,"正確。這是分割或讓與形成袋地的特別規則。"),c(2,"可任選任何陌生鄰地免費通行。",false,"錯誤。通行範圍限特定土地。"),c(3,"一定要比照第787條支付償金。",false,"錯誤。第789條明定無須支付。"),c(4,"分割形成袋地沒有通行救濟。",false,"錯誤。條文設有特別通行權。")],relatedArticles:["pb4-789"],essayPrompt:"比較第787條與第789條的袋地通行規則。",essayHint:"比較形成原因、通行範圍與償金。",tags:["袋地","分割","通行權"],imageUrl,legalBasis:"民法第789條"}
];
