const imageUrl="https://d2xsxph8kpxj0f.cloudfront.net/310519663221733224/gM5JgomKHbeiFYv994jtE8/obligation-016-C2jdVdwzMe8GTXf5KRNJqk.webp";
const c=(id:number,text:string,isCorrect:boolean,explanation:string)=>({id,text,isCorrect,explanation});
export const PROPERTY_BATCH_3_ARTICLES=[
 {id:"pb3-779",number:"第779條",title:"排水通過鄰地",content:"排泄家用或其他用水得通過鄰地，但須採鄰地損害最少處所方法並支付償金。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb3-781",number:"第781條",title:"水源地與井水使用",content:"水源地、井、溝渠及其他水流地所有人得自由使用其水，但法令或習慣另有規定者除外。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb3-782",number:"第782條",title:"水源污染的救濟",content:"他人杜絕、減少或污染水源，水源所有人得請求賠償；水為飲用或土地利用必要時得請求回復原狀。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb3-783",number:"第783條",title:"請求鄰地餘水",content:"家用或土地利用必要且非過鉅費勞不能得水者，得付償金請求鄰地給與餘水。",chapter:"相鄰關係",villageId:"property"},
 {id:"pb3-784",number:"第784條",title:"水流地水道變更",content:"水流地對岸屬他人時，水流地所有人不得變更水流或寬度。",chapter:"相鄰關係",villageId:"property"},
];
export const PROPERTY_BATCH_3_SCENARIOS=[
 {id:"property-031",villageId:"property",title:"排水管必經的鄰地",chapter:"相鄰關係",difficulty:"hard",story:["小安的家用排水若不經鄰地便無法排出。","她規劃穿越鄰地最短路線，卻會造成較大損害。"],question:"依民法第779條，何者正確？",choices:[c(1,"應選擇對鄰地損害最少的處所與方法並支付償金。",true,"正確。第779條同時要求最小損害與補償。"),c(2,"只要排水必要即可任意施工。",false,"錯誤。不得忽略最小損害與償金。"),c(3,"使用鄰地永遠無須付償金。",false,"錯誤。原則應支付償金。"),c(4,"鄰地損害越大越有利。",false,"錯誤。法定標準正相反。")],relatedArticles:["pb3-779"],essayPrompt:"說明排水通過權的限制與補償。",essayHint:"最小損害方案、償金及異議可請求法院決定。",tags:["排水","償金"],imageUrl,legalBasis:"民法第779條"},
 {id:"property-032",villageId:"property",title:"私有井水的灌溉",chapter:"相鄰關係",difficulty:"easy",story:["阿明擁有一口井，想用井水灌溉自家菜園。"],question:"依民法第781條，何者正確？",choices:[c(1,"井所有人原則得自由使用其水。",true,"正確，仍受法令或習慣等限制。"),c(2,"井所有人永遠不得用水。",false,"錯誤。條文原則是自由使用。"),c(3,"任何鄰居可無條件獨占井水。",false,"錯誤。題目先看水源所有人權能。"),c(4,"第781條只規定土地買賣。",false,"錯誤。規定水源與水流地利用。")],relatedArticles:["pb3-781"],essayPrompt:"說明第781條的原則與例外。",essayHint:"原則自由使用，注意法令或習慣另有規定。",tags:["井水","水源"],imageUrl,legalBasis:"民法第781條"},
 {id:"property-033",villageId:"property",title:"被施工污染的飲用井",chapter:"相鄰關係",difficulty:"hard",story:["工程將泥水排入阿美的井，使其飲用水遭污染。","該井水是阿美家中飲用所必要。"],question:"依民法第782條，何者正確？",choices:[c(1,"阿美得請求賠償，並得請求回復原狀。",true,"正確。飲用或土地利用必要的水源另有回復原狀救濟。"),c(2,"污染水源絕無任何救濟。",false,"錯誤。條文規定賠償及必要時回復。"),c(3,"只能請求回復，不能求償。",false,"錯誤。可請求損害賠償。"),c(4,"水源所有人不受保護。",false,"錯誤。第782條保護水源地或井所有人。")],relatedArticles:["pb3-782"],essayPrompt:"說明污染水源時的賠償與回復救濟。",essayHint:"注意飲用或土地利用必要才可請求回復原狀。",tags:["水源污染","回復原狀"],imageUrl,legalBasis:"民法第782條"},
 {id:"property-034",villageId:"property",title:"缺水農地的餘水請求",chapter:"相鄰關係",difficulty:"hard",story:["小農為灌溉土地，非花費過鉅費勞不能取得水，鄰地水源有餘水。"],question:"依民法第783條，何者正確？",choices:[c(1,"可支付償金請求鄰地給與餘水。",true,"正確。需有家用或土地利用必要且取得水過於困難。"),c(2,"可免費取得所有鄰地用水。",false,"錯誤。僅餘水且須支付償金。"),c(3,"不論是否困難均可請求。",false,"錯誤。有非過鉅費勞不能得水的要件。"),c(4,"只能購買自己的水源。",false,"錯誤。條文規定可向鄰地請求餘水。")],relatedArticles:["pb3-783"],essayPrompt:"列出請求鄰地餘水的要件。",essayHint:"必要、取得困難、餘水與償金。",tags:["餘水","農地"],imageUrl,legalBasis:"民法第783條"},
 {id:"property-035",villageId:"property",title:"私自加寬的溪溝",chapter:"相鄰關係",difficulty:"medium",story:["阿傑的水流地對岸屬鄰居，他為擴建庭院自行加寬並改變溪溝水流。"],question:"依民法第784條，何者正確？",choices:[c(1,"對岸屬他人時，阿傑不得變更水流或寬度。",true,"正確。第784條保障對岸土地。"),c(2,"只要土地是自己的就可任意改變。",false,"錯誤。水流地有特別限制。"),c(3,"水流寬度永遠不受規範。",false,"錯誤。條文明定不得變更。"),c(4,"只要通知鄰居即可改變。",false,"錯誤。條文並非單純通知制度。")],relatedArticles:["pb3-784"],essayPrompt:"說明水流地對岸屬他人時的限制。",essayHint:"比較兩岸均屬同一人時仍須留下游自然水路。",tags:["水流地","溪溝"],imageUrl,legalBasis:"民法第784條"}
];
